// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: api.go

package crit

import (
	"context"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
)

type apiClient struct {
	r *aoni.Client
}

func newAPI(doer any, opts ...aoni.ClientOption) *apiClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	targetReq := aoni.NewClient(doer, append([]aoni.ClientOption{option.WithBaseURL("https://crit.tf/api/v2/")}, baseOpts...)...)

	return &apiClient{
		r: targetReq,
	}
}

// NewAPI creates a new API client instance with preconfigured execution pipelines.
func NewAPI(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// New creates a new API client instance (alias for NewAPI).
func New(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// R returns the underlying *aoni.Client used by the client.
func (c *apiClient) R() *aoni.Client {
	return c.r
}

func (c *apiClient) FetchMyListings(ctx context.Context, mods ...aoni.RequestModifier) (*ListingsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[ListingsResponse](ctx, "listings/my", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) CreateListingDirect(ctx context.Context, req CreateListingRequest, mods ...aoni.RequestModifier) (*ListingsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[ListingsResponse](ctx, "listings", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) UpdateListingDirect(ctx context.Context, listingID string, req UpdateListingRequest, mods ...aoni.RequestModifier) (*ListingsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listing_id", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PutTo[ListingsResponse](ctx, "listings/{listing_id}", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) DeleteListing(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listing_id", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.DeleteTo[Response](ctx, "listings/{listing_id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) RefreshInventory(ctx context.Context, mods ...aoni.RequestModifier) (*InventoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[InventoryResponse](ctx, "inventory/refresh", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetMyGroup(ctx context.Context, mods ...aoni.RequestModifier) (*GroupResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[GroupResponse](ctx, "groups/my", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) InviteToGroupDirect(ctx context.Context, groupID int, req InviteGroupRequest, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("group_id", groupID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[Response](ctx, "groups/{group_id}/invite", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetPendingInvites(ctx context.Context, mods ...aoni.RequestModifier) (*InvitesResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[InvitesResponse](ctx, "groups/invites", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) AcceptGroupInvite(ctx context.Context, groupID int, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("group_id", groupID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[Response](ctx, "groups/{group_id}/accept", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) LeaveGroup(ctx context.Context, groupID int, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("group_id", groupID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[Response](ctx, "groups/{group_id}/leave", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) FetchAuthTokenDirect(ctx context.Context, mods ...aoni.RequestModifier) (*AuthTokenResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[AuthTokenResponse](ctx, "bot-api/auth-token", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) SendDeadMansRequestDirect(ctx context.Context, req DeadMansRequest, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[Response](ctx, "bot-api/alive", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetInventory(ctx context.Context, mods ...aoni.RequestModifier) (*InventoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[InventoryResponse](ctx, "inventory", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) UpdateTradeURLDirect(ctx context.Context, req UpdateTradeURLRequest, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PutTo[Response](ctx, "user/trade-url", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetUserInfo(ctx context.Context, mods ...aoni.RequestModifier) (*UserResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[UserResponse](ctx, "user", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
