// Code generated by aoni-gen. DO NOT EDIT.

package crit

import (
	"context"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

type apiClient struct {
	r request.Requester
}

func newAPI(doer any, opts ...aoni.ClientOption) *apiClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	var targetReq request.Requester
	if d, ok := doer.(aoni.RequestDoer); ok {
		targetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL("https://crit.tf/api/v2/")}, baseOpts...)...))
	} else if req, ok := doer.(request.Requester); ok {
		targetReq = request.AsRequester(aoni.Configure(req, append([]aoni.ClientOption{option.WithBaseURL("https://crit.tf/api/v2/")}, baseOpts...)...))
	} else if rd, ok := doer.(interface{ Rest() request.Requester }); ok && rd.Rest() != nil {
		targetReq = rd.Rest()
	} else if rd, ok := doer.(interface{ Requester() request.Requester }); ok && rd.Requester() != nil {
		targetReq = rd.Requester()
	} else {
		targetReq = request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL("https://crit.tf/api/v2/")}, baseOpts...)...))
	}

	return &apiClient{
		r: targetReq,
	}
}

// NewAPI creates a new API client instance with preconfigured execution pipelines.
func NewAPI(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// New creates a new API client instance (alias for NewAPI).
func New(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// R returns the underlying request.Requester used by the client.
func (c *apiClient) R() request.Requester {
	return c.r
}

func (c *apiClient) FetchMyListings(ctx context.Context, mods ...aoni.RequestModifier) (*ListingsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[ListingsResponse](ctx, c.r, "listings/my", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) CreateListingDirect(ctx context.Context, req CreateListingRequest, mods ...aoni.RequestModifier) (*ListingsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[ListingsResponse](ctx, c.r, "listings", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) UpdateListingDirect(ctx context.Context, listingID string, req UpdateListingRequest, mods ...aoni.RequestModifier) (*ListingsResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listing_id", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PutTo[ListingsResponse](ctx, c.r, "listings/{listing_id}", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) DeleteListing(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listing_id", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[Response](ctx, c.r, "listings/{listing_id}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) RefreshInventory(ctx context.Context, mods ...aoni.RequestModifier) (*InventoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[InventoryResponse](ctx, c.r, "inventory/refresh", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetMyGroup(ctx context.Context, mods ...aoni.RequestModifier) (*GroupResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[GroupResponse](ctx, c.r, "groups/my", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) InviteToGroupDirect(ctx context.Context, groupID int, req InviteGroupRequest, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("group_id", groupID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Response](ctx, c.r, "groups/{group_id}/invite", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetPendingInvites(ctx context.Context, mods ...aoni.RequestModifier) (*InvitesResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[InvitesResponse](ctx, c.r, "groups/invites", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) AcceptGroupInvite(ctx context.Context, groupID int, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("group_id", groupID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Response](ctx, c.r, "groups/{group_id}/accept", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) LeaveGroup(ctx context.Context, groupID int, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("group_id", groupID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Response](ctx, c.r, "groups/{group_id}/leave", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) FetchAuthTokenDirect(ctx context.Context, mods ...aoni.RequestModifier) (*AuthTokenResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[AuthTokenResponse](ctx, c.r, "bot-api/auth-token", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) SendDeadMansRequestDirect(ctx context.Context, req DeadMansRequest, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Response](ctx, c.r, "bot-api/alive", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetInventory(ctx context.Context, mods ...aoni.RequestModifier) (*InventoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[InventoryResponse](ctx, c.r, "inventory", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) UpdateTradeURLDirect(ctx context.Context, req UpdateTradeURLRequest, mods ...aoni.RequestModifier) (*Response, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PutTo[Response](ctx, c.r, "user/trade-url", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetUserInfo(ctx context.Context, mods ...aoni.RequestModifier) (*UserResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[UserResponse](ctx, c.r, "user", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
