// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: models.go

package crit

import (
	"net/url"
	"strconv"
)

// AppendFormData serializes CreateListingRequest into url-encoded form bytes on dst buffer (0 B/op).
func (r *CreateListingRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.AssetID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "asset_id="...)
		dst = append(dst, url.QueryEscape(r.AssetID)...)
	}
	if r.PriceKeys != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "price_keys="...)
		dst = strconv.AppendInt(dst, int64(r.PriceKeys), 10)
	}
	if r.PriceMetal != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "price_metal="...)
		dst = strconv.AppendFloat(dst, float64(r.PriceMetal), 'f', -1, 64)
	}

	return dst
}

// AppendQuery serializes CreateListingRequest into query string bytes on dst buffer (0 B/op).
func (r *CreateListingRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes CreateListingRequest into url.Values without reflection.
func (r *CreateListingRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.AssetID != "" {
		vals.Set("asset_id", r.AssetID)
	}
	if r.PriceKeys != 0 {
		vals.Set("price_keys", strconv.FormatInt(int64(r.PriceKeys), 10))
	}
	if r.PriceMetal != 0 {
		vals.Set("price_metal", strconv.FormatFloat(float64(r.PriceMetal), 'f', -1, 64))
	}
}

// AppendFormData serializes UpdateListingRequest into url-encoded form bytes on dst buffer (0 B/op).
func (r *UpdateListingRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.PriceKeys != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "price_keys="...)
		dst = strconv.AppendInt(dst, int64(r.PriceKeys), 10)
	}
	if r.PriceMetal != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "price_metal="...)
		dst = strconv.AppendFloat(dst, float64(r.PriceMetal), 'f', -1, 64)
	}

	return dst
}

// AppendQuery serializes UpdateListingRequest into query string bytes on dst buffer (0 B/op).
func (r *UpdateListingRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes UpdateListingRequest into url.Values without reflection.
func (r *UpdateListingRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.PriceKeys != 0 {
		vals.Set("price_keys", strconv.FormatInt(int64(r.PriceKeys), 10))
	}
	if r.PriceMetal != 0 {
		vals.Set("price_metal", strconv.FormatFloat(float64(r.PriceMetal), 'f', -1, 64))
	}
}

// AppendFormData serializes InviteGroupRequest into url-encoded form bytes on dst buffer (0 B/op).
func (r *InviteGroupRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.SteamID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "steam_id="...)
		dst = append(dst, url.QueryEscape(r.SteamID)...)
	}

	return dst
}

// AppendQuery serializes InviteGroupRequest into query string bytes on dst buffer (0 B/op).
func (r *InviteGroupRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes InviteGroupRequest into url.Values without reflection.
func (r *InviteGroupRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.SteamID != "" {
		vals.Set("steam_id", r.SteamID)
	}
}

// AppendFormData serializes DeadMansRequest into url-encoded form bytes on dst buffer (0 B/op).
func (r *DeadMansRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Alive {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "alive=true"...)
	}

	return dst
}

// AppendQuery serializes DeadMansRequest into query string bytes on dst buffer (0 B/op).
func (r *DeadMansRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes DeadMansRequest into url.Values without reflection.
func (r *DeadMansRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Alive {
		vals.Set("alive", "true")
	}
}

// AppendFormData serializes UpdateTradeURLRequest into url-encoded form bytes on dst buffer (0 B/op).
func (r *UpdateTradeURLRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.TradeURL != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "trade_url="...)
		dst = append(dst, url.QueryEscape(r.TradeURL)...)
	}

	return dst
}

// AppendQuery serializes UpdateTradeURLRequest into query string bytes on dst buffer (0 B/op).
func (r *UpdateTradeURLRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes UpdateTradeURLRequest into url.Values without reflection.
func (r *UpdateTradeURLRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.TradeURL != "" {
		vals.Set("trade_url", r.TradeURL)
	}
}

// AppendFormData serializes AuthTokenResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *AuthTokenResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.OK {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "ok=true"...)
	}
	if r.Token != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "token="...)
		dst = append(dst, url.QueryEscape(r.Token)...)
	}
	if r.Reason != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "reason="...)
		dst = append(dst, url.QueryEscape(r.Reason)...)
	}

	return dst
}

// AppendQuery serializes AuthTokenResponse into query string bytes on dst buffer (0 B/op).
func (r *AuthTokenResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes AuthTokenResponse into url.Values without reflection.
func (r *AuthTokenResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.OK {
		vals.Set("ok", "true")
	}
	if r.Token != "" {
		vals.Set("token", r.Token)
	}
	if r.Reason != "" {
		vals.Set("reason", r.Reason)
	}
}
