// Code generated by aoni-gen. DO NOT EDIT.

package bptf

import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

type apiClient struct {
	r request.Requester
}

func newAPI(doer any, opts ...aoni.ClientOption) *apiClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	var targetReq request.Requester
	if d, ok := doer.(aoni.RequestDoer); ok {
		targetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL("https://backpack.tf/api")}, baseOpts...)...))
	} else if req, ok := doer.(request.Requester); ok {
		targetReq = request.AsRequester(aoni.Configure(req, append([]aoni.ClientOption{option.WithBaseURL("https://backpack.tf/api")}, baseOpts...)...))
	} else if rd, ok := doer.(interface{ Rest() request.Requester }); ok && rd.Rest() != nil {
		targetReq = rd.Rest()
	} else if rd, ok := doer.(interface{ Requester() request.Requester }); ok && rd.Requester() != nil {
		targetReq = rd.Requester()
	} else {
		targetReq = request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL("https://backpack.tf/api")}, baseOpts...)...))
	}

	return &apiClient{
		r: targetReq,
	}
}

// NewAPI creates a new API client instance with preconfigured execution pipelines.
func NewAPI(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// New creates a new API client instance (alias for NewAPI).
func New(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// R returns the underlying request.Requester used by the client.
func (c *apiClient) R() request.Requester {
	return c.r
}

func (c *apiClient) Get(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetIgetCurrenciesV1(ctx context.Context, raw int, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "raw="...)
	qBytes = strconv.AppendInt(qBytes, int64(raw), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "IGetCurrencies/v1", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetIgetPriceHistoryV1(ctx context.Context, appid string, item string, quality string, tradable any, craftable string, priceindex string, mods ...aoni.RequestModifier) (*V1priceHistoryResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [256]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "appid="...)
	qBytes = append(qBytes, url.QueryEscape(appid)...)
	qBytes = append(qBytes, "&item="...)
	qBytes = append(qBytes, url.QueryEscape(item)...)
	qBytes = append(qBytes, "&quality="...)
	qBytes = append(qBytes, url.QueryEscape(quality)...)
	qBytes = append(qBytes, "&craftable="...)
	qBytes = append(qBytes, url.QueryEscape(craftable)...)
	qBytes = append(qBytes, "&priceindex="...)
	qBytes = append(qBytes, url.QueryEscape(priceindex)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	allMods = append(allMods, mod.WithQuery(tradable))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[V1priceHistoryResponse](ctx, c.r, "IGetPriceHistory/v1", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetIgetPricesV4(ctx context.Context, raw int, since int, mods ...aoni.RequestModifier) (*V4pricesResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "raw="...)
	qBytes = strconv.AppendInt(qBytes, int64(raw), 10)
	qBytes = append(qBytes, "&since="...)
	qBytes = strconv.AppendInt(qBytes, int64(since), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[V4pricesResponse](ctx, c.r, "IGetPrices/v4", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetIgetSpecialItemsV1(ctx context.Context, appid int, mods ...aoni.RequestModifier) (*SpecialItemsResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "appid="...)
	qBytes = strconv.AppendInt(qBytes, int64(appid), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[SpecialItemsResponse](ctx, c.r, "IGetSpecialItems/v1", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetIgetUsersGetImpersonatedUsers(ctx context.Context, limit int, skip int, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "limit="...)
	qBytes = strconv.AppendInt(qBytes, int64(limit), 10)
	qBytes = append(qBytes, "&skip="...)
	qBytes = strconv.AppendInt(qBytes, int64(skip), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "IGetUsers/GetImpersonatedUsers", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetIgetUsersV3(ctx context.Context, steamid []string, steamids []string, mods ...aoni.RequestModifier) (any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "steamid="...)
	qBytes = append(qBytes, url.QueryEscape(fmt.Sprint(steamid))...)
	qBytes = append(qBytes, "&steamids="...)
	qBytes = append(qBytes, url.QueryEscape(fmt.Sprint(steamids))...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[any](ctx, c.r, "IGetUsers/v3", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostAgentPulse(ctx context.Context, mods ...aoni.RequestModifier) (*UserAgentStatus, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[UserAgentStatus](ctx, c.r, "agent/pulse", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostAgentStatus(ctx context.Context, mods ...aoni.RequestModifier) (*UserAgentStatus, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[UserAgentStatus](ctx, c.r, "agent/status", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostAgentStop(ctx context.Context, mods ...aoni.RequestModifier) (*UserAgentStatus, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[UserAgentStatus](ctx, c.r, "agent/stop", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetClassifiedsAlerts(ctx context.Context, skip int, limit int, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "skip="...)
	qBytes = strconv.AppendInt(qBytes, int64(skip), 10)
	qBytes = append(qBytes, "&limit="...)
	qBytes = strconv.AppendInt(qBytes, int64(limit), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "classifieds/alerts", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostClassifiedsAlerts(ctx context.Context, itemName string, intent string, currency string, min int, max int, blanket int, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [256]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "item_name="...)
	qBytes = append(qBytes, url.QueryEscape(itemName)...)
	qBytes = append(qBytes, "&intent="...)
	qBytes = append(qBytes, url.QueryEscape(intent)...)
	qBytes = append(qBytes, "&currency="...)
	qBytes = append(qBytes, url.QueryEscape(currency)...)
	qBytes = append(qBytes, "&min="...)
	qBytes = strconv.AppendInt(qBytes, int64(min), 10)
	qBytes = append(qBytes, "&max="...)
	qBytes = strconv.AppendInt(qBytes, int64(max), 10)
	qBytes = append(qBytes, "&blanket="...)
	qBytes = strconv.AppendInt(qBytes, int64(blanket), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[map[string]any](ctx, c.r, "classifieds/alerts", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) DeleteClassifiedsAlerts(ctx context.Context, itemName string, intent string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "item_name="...)
	qBytes = append(qBytes, url.QueryEscape(itemName)...)
	qBytes = append(qBytes, "&intent="...)
	qBytes = append(qBytes, url.QueryEscape(intent)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "classifieds/alerts", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetClassifiedsAlertsByID(ctx context.Context, iD string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", iD))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "classifieds/alerts/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) DeleteClassifiedsAlertsByID(ctx context.Context, iD string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", iD))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "classifieds/alerts/{id}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) DeleteClassifiedsDeleteV1(ctx context.Context, req any, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(req))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "classifieds/delete/v1", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostClassifiedsListV1(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[map[string]any](ctx, c.r, "classifieds/list/v1", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetClassifiedsListingsV1(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "classifieds/listings/v1", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostInventoryBySteamidRefresh(ctx context.Context, steamid string, mods ...aoni.RequestModifier) (*InventoryStatus, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("steamid", steamid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[InventoryStatus](ctx, c.r, "inventory/{steamid}/refresh", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetInventoryBySteamidStatus(ctx context.Context, steamid string, mods ...aoni.RequestModifier) (*InventoryStatus, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("steamid", steamid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[InventoryStatus](ctx, c.r, "inventory/{steamid}/status", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetInventoryBySteamidValues(ctx context.Context, steamid string, mods ...aoni.RequestModifier) (*InventoryValues, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("steamid", steamid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[InventoryValues](ctx, c.r, "inventory/{steamid}/values", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetNotifications(ctx context.Context, skip int, limit int, unread int, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [128]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "skip="...)
	qBytes = strconv.AppendInt(qBytes, int64(skip), 10)
	qBytes = append(qBytes, "&limit="...)
	qBytes = strconv.AppendInt(qBytes, int64(limit), 10)
	qBytes = append(qBytes, "&unread="...)
	qBytes = strconv.AppendInt(qBytes, int64(unread), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "notifications", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostNotificationsMark(ctx context.Context, mods ...aoni.RequestModifier) (*NotificationMarkState, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[NotificationMarkState](ctx, c.r, "notifications/mark", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostNotificationsUnread(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[map[string]any](ctx, c.r, "notifications/unread", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetNotificationsByID(ctx context.Context, iD string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", iD))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "notifications/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) DeleteNotificationsByID(ctx context.Context, iD string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", iD))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "notifications/{id}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetUsersInfoV1(ctx context.Context, steamids string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "steamids="...)
	qBytes = append(qBytes, url.QueryEscape(steamids)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "users/info/v1", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetV2ClassifiedsArchive(ctx context.Context, skip int, limit int, mods ...aoni.RequestModifier) (*ListingScrollable, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "skip="...)
	qBytes = strconv.AppendInt(qBytes, int64(skip), 10)
	qBytes = append(qBytes, "&limit="...)
	qBytes = strconv.AppendInt(qBytes, int64(limit), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[ListingScrollable](ctx, c.r, "v2/classifieds/archive", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) DeleteV2ClassifiedsArchive(ctx context.Context, req ListingDropRequest, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(req))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/archive", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetV2ClassifiedsArchiveBatch(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "v2/classifieds/archive/batch", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) DeleteV2ClassifiedsArchiveBatch(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/archive/batch", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetV2ClassifiedsArchiveByListingID(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[Listing](ctx, c.r, "v2/classifieds/archive/{listingId}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) DeleteV2ClassifiedsArchiveByListingID(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/archive/{listingId}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PatchV2ClassifiedsArchiveByListingID(ctx context.Context, listingID string, req ListingPatchRequest, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PatchTo[Listing](ctx, c.r, "v2/classifieds/archive/{listingId}", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostV2ClassifiedsArchiveByListingIDPublish(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Listing](ctx, c.r, "v2/classifieds/archive/{listingId}/publish", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetV2ClassifiedsListings(ctx context.Context, skip int, limit int, bumpedSince int, createdSince int, mods ...aoni.RequestModifier) (*ListingScrollable, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [256]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "skip="...)
	qBytes = strconv.AppendInt(qBytes, int64(skip), 10)
	qBytes = append(qBytes, "&limit="...)
	qBytes = strconv.AppendInt(qBytes, int64(limit), 10)
	qBytes = append(qBytes, "&bumped_since="...)
	qBytes = strconv.AppendInt(qBytes, int64(bumpedSince), 10)
	qBytes = append(qBytes, "&created_since="...)
	qBytes = strconv.AppendInt(qBytes, int64(createdSince), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[ListingScrollable](ctx, c.r, "v2/classifieds/listings", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostV2ClassifiedsListings(ctx context.Context, req ListingResolvable, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) DeleteV2ClassifiedsListings(ctx context.Context, req ListingDropRequest, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(req))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/listings", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostV2ClassifiedsListingsArchiveAll(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[map[string]any](ctx, c.r, "v2/classifieds/listings/archiveAll", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetV2ClassifiedsListingsBatch(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "v2/classifieds/listings/batch", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostV2ClassifiedsListingsBatch(ctx context.Context, req []ListingResolvable, mods ...aoni.RequestModifier) ([]*ListingBatchCreateResult, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[[]*ListingBatchCreateResult](ctx, c.r, "v2/classifieds/listings/batch", req, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) DeleteV2ClassifiedsListingsBatch(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/listings/batch", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PostV2ClassifiedsListingsPublishAll(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[map[string]any](ctx, c.r, "v2/classifieds/listings/publishAll", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetV2ClassifiedsListingsByListingID(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) DeleteV2ClassifiedsListingsByListingID(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/listings/{listingId}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PatchV2ClassifiedsListingsByListingID(ctx context.Context, listingID string, req ListingPatchRequest, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PatchTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostV2ClassifiedsListingsByListingIDArchive(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}/archive", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostV2ClassifiedsListingsByListingIDDemote(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}/demote", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostV2ClassifiedsListingsByListingIDPromote(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("listingId", listingID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}/promote", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
