// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by aoni "openapi -spec swagger.json -pkg bptf -skip-deprecated -fast -include-path (v2/classifieds|agent|inventory|classifieds/alerts|notifications) -include-path IGet(Prices|Currencies|PriceHistory|Users) -include-path users/info"
// 
// DO NOT EDIT.

package bptf

import (
	"context"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

// BaseURL is the default API base endpoint.
const BaseURL = "https://backpack.tf/api/"

// AppID — Steam App ID.
type AppID int

type ClassifiedsResourceLimits struct {
	Listings map[string]any `json:"listings,omitempty"`
}

// CraftableEnum — Craftability identifier.
type CraftableEnum string

type Currency struct {
	Active     int           `json:"active,omitempty"`
	Craftable  string        `json:"craftable,omitempty"`
	Defindex   int           `json:"defindex,omitempty"`
	Name       string        `json:"name,omitempty"`
	Plural     string        `json:"plural,omitempty"`
	Price      V4PricesEntry `json:"price,omitempty"`
	Priceindex Priceindex    `json:"priceindex,omitempty"`
	Quality    string        `json:"quality,omitempty"`
	Round      int           `json:"round,omitempty"`
	Single     string        `json:"single,omitempty"`
}

type Cursor struct {
	Limit int `json:"limit,omitempty"`
	Skip  int `json:"skip,omitempty"`
	Total int `json:"total,omitempty"`
}

// Entity — An item attribute that usually has an accompanying name, id, maybe a colour.
type Entity struct {
	Color string `json:"color,omitempty"`
	ID    int    `json:"id,omitempty"`
	Name  string `json:"name,omitempty"`
}

type ImpersonatedUser struct {
	Avatar      string `json:"avatar,omitempty"`
	Personaname string `json:"personaname,omitempty"`
	SteamID     string `json:"steamid,omitempty"`
}

// InventoryStatus — Inventory status
type InventoryStatus struct {
	CurrentTime     int `json:"current_time,omitempty"`
	LastUpdate      int `json:"last_update,omitempty"`
	NextUpdate      int `json:"next_update,omitempty"`
	RefreshInterval int `json:"refresh_interval,omitempty"`
	Timestamp       int `json:"timestamp,omitempty"`
}

// InventoryValues — Inventory values
type InventoryValues struct {
	MarketValue any `json:"market_value,omitempty"`
	Value       any `json:"value,omitempty"`
}

// ItemDocument — The V2 item document, returned in listing responses and used as an input in various V2 APIs
type ItemDocument struct {
	BaseName        string `json:"baseName,omitempty"`
	ElevatedQuality Entity `json:"elevatedQuality,omitempty"`
	ImageURL        string `json:"imageUrl,omitempty"`
	Name            string `json:"name,omitempty"`
	Paint           Entity `json:"paint,omitempty"`
	Particle        Entity `json:"particle,omitempty"`
	Quality         Entity `json:"quality,omitempty"`
	Quantity        int    `json:"quantity,omitempty"`
	Rarity          Entity `json:"rarity,omitempty"`
}

type ItemResolvable struct {
	Craftable  CraftableEnum `json:"craftable,omitempty"`
	Item       string        `json:"item,omitempty"`
	Priceindex Priceindex    `json:"priceindex,omitempty"`
	Quality    string        `json:"quality,omitempty"`
	Tradable   TradableEnum  `json:"tradable,omitempty"`
}

type Listing struct {
	AppID                int               `json:"appid,omitempty"`
	BumpedAt             string            `json:"bumpedAt,omitempty"`
	BuyoutOnly           bool              `json:"buyoutOnly,omitempty"`
	Count                int               `json:"count,omitempty"`
	Currencies           ListingCurrencies `json:"currencies,omitempty"`
	Details              string            `json:"details,omitempty"`
	ID                   string            `json:"id,omitempty"`
	Intent               ListingIntent     `json:"intent,omitempty"`
	Item                 ItemDocument      `json:"item,omitempty"`
	ListedAt             string            `json:"listedAt,omitempty"`
	Promoted             bool              `json:"promoted,omitempty"`
	SteamID              string            `json:"steamid,omitempty"`
	TradeOffersPreferred bool              `json:"tradeOffersPreferred,omitempty"`
}

// ListingBatchCreateResult — A result object containing either a listing or an error.
type ListingBatchCreateResult struct {
	Error  ResponseError `json:"error,omitempty"`
	Result Listing       `json:"result,omitempty"`
}

// ListingCurrencies — A key-value map of currency IDs to values.
type ListingCurrencies string

type ListingDropRequest struct {
	Intent string `json:"intent,omitempty"`
}

// ListingIntent — Listing intent.
type ListingIntent string

// ListingPatchRequest — Listing PATCH request body
type ListingPatchRequest struct {
	Currencies ListingCurrencies `json:"currencies,omitempty"`
	Details    string            `json:"details,omitempty"`
	Quantity   int               `json:"quantity,omitempty"`
}

type ListingResolvable struct {
	Currencies ListingCurrencies `json:"currencies,omitempty"`
	Details    string            `json:"details,omitempty"`
	ID         int               `json:"id,omitempty"`
	Item       any               `json:"item,omitempty"`
}

type ListingScrollable struct {
	Cursor  Cursor    `json:"cursor,omitempty"`
	Results []Listing `json:"results,omitempty"`
}

type NotificationMarkState struct {
	Modified int `json:"modified,omitempty"`
}

// Priceindex —
type Priceindex string

type ResponseError struct {
	Message string `json:"message,omitempty"`
	Reason  string `json:"reason,omitempty"`
}

// SchemaItem — Schema item
type SchemaItem struct {
}

type SpecialItemsResponse struct {
	Response map[string]any `json:"response,omitempty"`
}

// SuccessBoolProp — A success bool prop will be found on older APIs before we learned to use status codes to determine response success
type SuccessBoolProp int

// TradableEnum — Tradability identifier.
type TradableEnum string

// UserAgentStatus — User agent status.
type UserAgentStatus struct {
	Client      string `json:"client,omitempty"`
	CurrentTime int    `json:"current_time,omitempty"`
	ExpireAt    int    `json:"expire_at,omitempty"`
	Status      string `json:"status,omitempty"`
}

type V1PriceHistoryNode struct {
	Currency  string  `json:"currency,omitempty"`
	Timestamp int     `json:"timestamp,omitempty"`
	Value     float64 `json:"value,omitempty"`
	ValueHigh float64 `json:"value_high,omitempty"`
}

type V1PriceHistoryResponse struct {
	History []V1PriceHistoryNode `json:"history,omitempty"`
	Success any                  `json:"success,omitempty"`
}

// V1User — user info doc
type V1User struct {
	Admin               string `json:"admin,omitempty"`
	Avatar              string `json:"avatar,omitempty"`
	Bans                string `json:"bans,omitempty"`
	Donated             string `json:"donated,omitempty"`
	Integrations        string `json:"integrations,omitempty"`
	Inventory           string `json:"inventory,omitempty"`
	LastOnline          string `json:"last_online,omitempty"`
	Name                string `json:"name,omitempty"`
	Premium             string `json:"premium,omitempty"`
	PremiumMonthsGifted int    `json:"premium_months_gifted,omitempty"`
	Trust               any    `json:"trust,omitempty"`
	Voting              any    `json:"voting,omitempty"`
}

type V1UserTrust struct {
	Negative int `json:"negative,omitempty"`
	Positive int `json:"positive,omitempty"`
}

type V1UserVoting string

type V4CraftableDict struct {
	Craftable    V4PriceindexDict `json:"Craftable,omitempty"`
	NonCraftable V4PriceindexDict `json:"Non-Craftable,omitempty"`
}

type V4PriceindexDict string

type V4PricesBaseItemDoc struct {
	Defindex []string       `json:"defindex,omitempty"`
	Prices   map[string]any `json:"prices,omitempty"`
}

type V4PricesEntry struct {
	Australium   int     `json:"australium,omitempty"`
	Currency     string  `json:"currency,omitempty"`
	Difference   float64 `json:"difference,omitempty"`
	LastUpdate   int     `json:"last_update,omitempty"`
	Value        float64 `json:"value,omitempty"`
	ValueHigh    float64 `json:"value_high,omitempty"`
	ValueRaw     float64 `json:"value_raw,omitempty"`
	ValueRawHigh float64 `json:"value_raw_high,omitempty"`
}

type V4PricesResponse struct {
	CurrentTime      int             `json:"current_time,omitempty"`
	Items            map[string]any  `json:"items,omitempty"`
	Message          string          `json:"message,omitempty"`
	RawUsdValue      int             `json:"raw_usd_value,omitempty"`
	Success          SuccessBoolProp `json:"success,omitempty"`
	UsdCurrency      string          `json:"usd_currency,omitempty"`
	UsdCurrencyIndex int             `json:"usd_currency_index,omitempty"`
}

type V4TradableDict struct {
	NonTradable V4CraftableDict `json:"Non-Tradable,omitempty"`
	Tradable    V4CraftableDict `json:"Tradable,omitempty"`
}

// Client is a thread-safe HTTP API client backed by aoni.
type Client struct {
	r request.Requester
}

// New instantiates a new Client wrapper.
func New(doer aoni.RequestDoer, apiKey string, userToken string, opts ...aoni.ClientOption) *Client {
	if doer == nil {
		doer = fast.NewClient()
	}

	defaultOpts := []aoni.ClientOption{
		option.WithBaseURL(BaseURL),
	}
	if apiKey != "" {
		defaultOpts = append(defaultOpts, option.WithModifiers(mod.WithQuery(struct {
			Key string `url:"key"`
		}{apiKey})))
	}
	if userToken != "" {
		defaultOpts = append(defaultOpts, option.WithHeader("X-Auth-Token", userToken))
	}
	defaultOpts = append(defaultOpts, opts...)

	return &Client{
		r: request.AsRequester(aoni.Configure(doer, defaultOpts...)),
	}
}

// With returns a cloned Client with the given options applied.
func (c *Client) With(opts ...aoni.ClientOption) *Client {
	if len(opts) == 0 {
		return c
	}
	return &Client{
		r: request.AsRequester(aoni.Configure(c.r, opts...)),
	}
}

// R yields the underlying low-level Requester.
func (c *Client) R() request.Requester {
	return c.r
}

// PostClassifiedsListingsPublishAllV2 — Publish all listings
// Route: POST /v2/classifieds/listings/publishAll
func (c *Client) PostClassifiedsListingsPublishAllV2(ctx context.Context, mods ...aoni.RequestModifier) error {
	_, err := request.PostTo[request.NoResponse](ctx, c.r, "v2/classifieds/listings/publishAll", nil, mods...)
	return err
}

// DeleteClassifiedsListingsBatchV2 — Batch delete listings
// Route: DELETE /v2/classifieds/listings/batch
func (c *Client) DeleteClassifiedsListingsBatchV2(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/listings/batch", nil, mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsListingsBatchV2 — Get batch operation limit
// Route: GET /v2/classifieds/listings/batch
func (c *Client) GetClassifiedsListingsBatchV2(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.GetTo[map[string]any](ctx, c.r, "v2/classifieds/listings/batch", mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// PostClassifiedsListingsBatchV2 — Batch create listings
// Route: POST /v2/classifieds/listings/batch
func (c *Client) PostClassifiedsListingsBatchV2(ctx context.Context, body []ListingResolvable, mods ...aoni.RequestModifier) (*[]ListingBatchCreateResult, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PostTo[[]ListingBatchCreateResult](ctx, c.r, "v2/classifieds/listings/batch", body, allMods...)
}

// PostClassifiedsListingsArchiveAllV2 — Archive all listings
// Route: POST /v2/classifieds/listings/archiveAll
func (c *Client) PostClassifiedsListingsArchiveAllV2(ctx context.Context, mods ...aoni.RequestModifier) error {
	_, err := request.PostTo[request.NoResponse](ctx, c.r, "v2/classifieds/listings/archiveAll", nil, mods...)
	return err
}

// DeleteClassifiedsListingsV2 — Delete all listings
// Route: DELETE /v2/classifieds/listings
func (c *Client) DeleteClassifiedsListingsV2(ctx context.Context, body ListingDropRequest, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/listings", body, mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsListingsV2 — Get account listings
// Route: GET /v2/classifieds/listings
func (c *Client) GetClassifiedsListingsV2(ctx context.Context, query GetClassifiedsListingsV2Query, mods ...aoni.RequestModifier) (*ListingScrollable, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	return request.GetTo[ListingScrollable](ctx, c.r, "v2/classifieds/listings", allMods...)
}

// GetClassifiedsListingsV2Query encapsulates query parameters for the request.
type GetClassifiedsListingsV2Query struct {
	Skip         int `url:"skip,omitempty"`
	Limit        int `url:"limit,omitempty"`
	BumpedSince  int `url:"bumpedSince,omitempty"`
	CreatedSince int `url:"createdSince,omitempty"`
}

// PostClassifiedsListingsV2 — Create one listing
// Route: POST /v2/classifieds/listings
func (c *Client) PostClassifiedsListingsV2(ctx context.Context, body ListingResolvable, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings", body, allMods...)
}

// DeleteClassifiedsArchiveBatchV2 — Batch delete archived listings
// Route: DELETE /v2/classifieds/archive/batch
func (c *Client) DeleteClassifiedsArchiveBatchV2(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/archive/batch", nil, mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsArchiveBatchV2 — Get batch operation limit
// Route: GET /v2/classifieds/archive/batch
func (c *Client) GetClassifiedsArchiveBatchV2(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.GetTo[map[string]any](ctx, c.r, "v2/classifieds/archive/batch", mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// DeleteClassifiedsArchiveV2 — Delete all archived listings
// Route: DELETE /v2/classifieds/archive
func (c *Client) DeleteClassifiedsArchiveV2(ctx context.Context, body ListingDropRequest, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/archive", body, mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsArchiveV2 — Get account archived listings
// Route: GET /v2/classifieds/archive
func (c *Client) GetClassifiedsArchiveV2(ctx context.Context, query GetClassifiedsArchiveV2Query, mods ...aoni.RequestModifier) (*ListingScrollable, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	return request.GetTo[ListingScrollable](ctx, c.r, "v2/classifieds/archive", allMods...)
}

// GetClassifiedsArchiveV2Query encapsulates query parameters for the request.
type GetClassifiedsArchiveV2Query struct {
	Skip  int `url:"skip,omitempty"`
	Limit int `url:"limit,omitempty"`
}

// GetUsersInfoV1 — Get user info
// Route: GET /users/info/v1
func (c *Client) GetUsersInfoV1(ctx context.Context, query GetUsersInfoV1Query, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	resp, err := request.GetTo[map[string]any](ctx, c.r, "users/info/v1", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetUsersInfoV1Query encapsulates query parameters for the request.
type GetUsersInfoV1Query struct {
	Steamids string `url:"steamids,omitempty"`
}

// PostNotificationsUnread — Get unread notifications and mark them as read
// Route: POST /notifications/unread
func (c *Client) PostNotificationsUnread(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.PostTo[map[string]any](ctx, c.r, "notifications/unread", nil, mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// PostNotificationsMark — Mark unread notifications as read
// Route: POST /notifications/mark
func (c *Client) PostNotificationsMark(ctx context.Context, mods ...aoni.RequestModifier) (*NotificationMarkState, error) {
	return request.PostTo[NotificationMarkState](ctx, c.r, "notifications/mark", nil, mods...)
}

// GetNotifications — Get notifications
// Route: GET /notifications
func (c *Client) GetNotifications(ctx context.Context, query GetNotificationsQuery, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	resp, err := request.GetTo[map[string]any](ctx, c.r, "notifications", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetNotificationsQuery encapsulates query parameters for the request.
type GetNotificationsQuery struct {
	Skip   int `url:"skip,omitempty"`
	Limit  int `url:"limit,omitempty"`
	Unread int `url:"unread,omitempty"`
}

// DeleteClassifiedsAlerts — Delete an alert by item name and intent
// Route: DELETE /classifieds/alerts
func (c *Client) DeleteClassifiedsAlerts(ctx context.Context, query DeleteClassifiedsAlertsQuery, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "classifieds/alerts", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// DeleteClassifiedsAlertsQuery encapsulates query parameters for the request.
type DeleteClassifiedsAlertsQuery struct {
	ItemName string        `url:"item_name,omitempty"`
	Intent   ListingIntent `url:"intent,omitempty"`
}

// GetClassifiedsAlerts — Get alerts
// Route: GET /classifieds/alerts
func (c *Client) GetClassifiedsAlerts(ctx context.Context, query GetClassifiedsAlertsQuery, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	resp, err := request.GetTo[map[string]any](ctx, c.r, "classifieds/alerts", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsAlertsQuery encapsulates query parameters for the request.
type GetClassifiedsAlertsQuery struct {
	Skip  int `url:"skip,omitempty"`
	Limit int `url:"limit,omitempty"`
}

// PostClassifiedsAlerts — Create alert
// Route: POST /classifieds/alerts
func (c *Client) PostClassifiedsAlerts(ctx context.Context, query PostClassifiedsAlertsQuery, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	resp, err := request.PostTo[map[string]any](ctx, c.r, "classifieds/alerts", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// PostClassifiedsAlertsQuery encapsulates query parameters for the request.
type PostClassifiedsAlertsQuery struct {
	ItemName string        `url:"item_name,omitempty"`
	Intent   ListingIntent `url:"intent,omitempty"`
	Currency string        `url:"currency,omitempty"`
	Min      int           `url:"min,omitempty"`
	Max      int           `url:"max,omitempty"`
	Blanket  int           `url:"blanket,omitempty"`
}

// PostAgentStop — Unregister a user agent
// Route: POST /agent/stop
func (c *Client) PostAgentStop(ctx context.Context, mods ...aoni.RequestModifier) (*UserAgentStatus, error) {
	return request.PostTo[UserAgentStatus](ctx, c.r, "agent/stop", nil, mods...)
}

// PostAgentStatus — Get agent status
// Route: POST /agent/status
func (c *Client) PostAgentStatus(ctx context.Context, mods ...aoni.RequestModifier) (*UserAgentStatus, error) {
	return request.PostTo[UserAgentStatus](ctx, c.r, "agent/status", nil, mods...)
}

// PostAgentPulse — (Re)-register a user agent
// Route: POST /agent/pulse
func (c *Client) PostAgentPulse(ctx context.Context, mods ...aoni.RequestModifier) (*UserAgentStatus, error) {
	return request.PostTo[UserAgentStatus](ctx, c.r, "agent/pulse", nil, mods...)
}

// GetIgetUsersV3 — Get user data
// Route: GET /IGetUsers/v3
func (c *Client) GetIgetUsersV3(ctx context.Context, query GetIgetUsersV3Query, mods ...aoni.RequestModifier) (*any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	return request.GetTo[any](ctx, c.r, "IGetUsers/v3", allMods...)
}

// GetIgetUsersV3Query encapsulates query parameters for the request.
type GetIgetUsersV3Query struct {
	SteamID  []string `url:"steamid,omitempty"`
	Steamids []string `url:"steamids,omitempty"`
}

// GetIgetUsersGetImpersonatedUsers — Get impersonated users
// Route: GET /IGetUsers/GetImpersonatedUsers
func (c *Client) GetIgetUsersGetImpersonatedUsers(ctx context.Context, query GetIgetUsersGetImpersonatedUsersQuery, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	resp, err := request.GetTo[map[string]any](ctx, c.r, "IGetUsers/GetImpersonatedUsers", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetIgetUsersGetImpersonatedUsersQuery encapsulates query parameters for the request.
type GetIgetUsersGetImpersonatedUsersQuery struct {
	Limit int `url:"limit,omitempty"`
	Skip  int `url:"skip,omitempty"`
}

// GetIgetPricesV4 — Get price schema
// Route: GET /IGetPrices/v4
func (c *Client) GetIgetPricesV4(ctx context.Context, query GetIgetPricesV4Query, mods ...aoni.RequestModifier) (*V4PricesResponse, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	return request.GetTo[V4PricesResponse](ctx, c.r, "IGetPrices/v4", allMods...)
}

// GetIgetPricesV4Query encapsulates query parameters for the request.
type GetIgetPricesV4Query struct {
	Raw   int `url:"raw,omitempty"`
	Since int `url:"since,omitempty"`
}

// GetIgetPriceHistoryV1 — Returns price history for an item
// Route: GET /IGetPriceHistory/v1
func (c *Client) GetIgetPriceHistoryV1(ctx context.Context, query GetIgetPriceHistoryV1Query, mods ...aoni.RequestModifier) (*V1PriceHistoryResponse, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	return request.GetTo[V1PriceHistoryResponse](ctx, c.r, "IGetPriceHistory/v1", allMods...)
}

// GetIgetPriceHistoryV1Query encapsulates query parameters for the request.
type GetIgetPriceHistoryV1Query struct {
	AppID      string        `url:"appid,omitempty"`
	Item       string        `url:"item,omitempty"`
	Quality    string        `url:"quality,omitempty"`
	Tradable   TradableEnum  `url:"tradable,omitempty"`
	Craftable  CraftableEnum `url:"craftable,omitempty"`
	Priceindex Priceindex    `url:"priceindex,omitempty"`
}

// GetIgetCurrenciesV1 — Returns internal currency data for a given game
// Route: GET /IGetCurrencies/v1
func (c *Client) GetIgetCurrenciesV1(ctx context.Context, query GetIgetCurrenciesV1Query, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
	}, mods...)

	resp, err := request.GetTo[map[string]any](ctx, c.r, "IGetCurrencies/v1", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetIgetCurrenciesV1Query encapsulates query parameters for the request.
type GetIgetCurrenciesV1Query struct {
	Raw int `url:"raw,omitempty"`
}

// PostClassifiedsListingsByListingIDPromoteV2 — Promote this listing
// Route: POST /v2/classifieds/listings/{listingId}/promote
func (c *Client) PostClassifiedsListingsByListingIDPromoteV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}/promote", nil, allMods...)
}

// PostClassifiedsListingsByListingIDDemoteV2 — Demote this listing
// Route: POST /v2/classifieds/listings/{listingId}/demote
func (c *Client) PostClassifiedsListingsByListingIDDemoteV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}/demote", nil, allMods...)
}

// PostClassifiedsListingsByListingIDArchiveV2 — Move listing to the archive
// Route: POST /v2/classifieds/listings/{listingId}/archive
func (c *Client) PostClassifiedsListingsByListingIDArchiveV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PostTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}/archive", nil, allMods...)
}

// DeleteClassifiedsListingsByListingIDV2 — Delete one listing
// Route: DELETE /v2/classifieds/listings/{listingId}
func (c *Client) DeleteClassifiedsListingsByListingIDV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/listings/{listingId}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsListingsByListingIDV2 — Get one listing
// Route: GET /v2/classifieds/listings/{listingId}
func (c *Client) GetClassifiedsListingsByListingIDV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.GetTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}", allMods...)
}

// PatchClassifiedsListingsByListingIDV2 — Update one listing
// Route: PATCH /v2/classifieds/listings/{listingId}
func (c *Client) PatchClassifiedsListingsByListingIDV2(ctx context.Context, listingID string, body ListingPatchRequest, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PatchTo[Listing](ctx, c.r, "v2/classifieds/listings/{listingId}", body, allMods...)
}

// PostClassifiedsArchiveByListingIDPublishV2 — Publish one archived listing to the active pool
// Route: POST /v2/classifieds/archive/{listingId}/publish
func (c *Client) PostClassifiedsArchiveByListingIDPublishV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PostTo[Listing](ctx, c.r, "v2/classifieds/archive/{listingId}/publish", nil, allMods...)
}

// DeleteClassifiedsArchiveByListingIDV2 — Delete one archived listing
// Route: DELETE /v2/classifieds/archive/{listingId}
func (c *Client) DeleteClassifiedsArchiveByListingIDV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "v2/classifieds/archive/{listingId}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsArchiveByListingIDV2 — Get one archived listing
// Route: GET /v2/classifieds/archive/{listingId}
func (c *Client) GetClassifiedsArchiveByListingIDV2(ctx context.Context, listingID string, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.GetTo[Listing](ctx, c.r, "v2/classifieds/archive/{listingId}", allMods...)
}

// PatchClassifiedsArchiveByListingIDV2 — Update one archived listing
// Route: PATCH /v2/classifieds/archive/{listingId}
func (c *Client) PatchClassifiedsArchiveByListingIDV2(ctx context.Context, listingID string, body ListingPatchRequest, mods ...aoni.RequestModifier) (*Listing, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("listingId", listingID),
		mod.WithErrorModel(&ResponseError{}),
	}, mods...)

	return request.PatchTo[Listing](ctx, c.r, "v2/classifieds/archive/{listingId}", body, allMods...)
}

// DeleteNotificationsByID — Delete notification
// Route: DELETE /notifications/{id}
func (c *Client) DeleteNotificationsByID(ctx context.Context, id string, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("id", id),
	}, mods...)

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "notifications/{id}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetNotificationsByID — Get notification
// Route: GET /notifications/{id}
func (c *Client) GetNotificationsByID(ctx context.Context, id string, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("id", id),
	}, mods...)

	resp, err := request.GetTo[map[string]any](ctx, c.r, "notifications/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetInventoryBySteamIDValues — Get inventory values.
// Route: GET /inventory/{steamid}/values
func (c *Client) GetInventoryBySteamIDValues(ctx context.Context, mods ...aoni.RequestModifier) (*InventoryValues, error) {
	return request.GetTo[InventoryValues](ctx, c.r, "inventory/{steamid}/values", mods...)
}

// GetInventoryBySteamIDStatus — Get the status of an inventory.
// Route: GET /inventory/{steamid}/status
func (c *Client) GetInventoryBySteamIDStatus(ctx context.Context, mods ...aoni.RequestModifier) (*InventoryStatus, error) {
	return request.GetTo[InventoryStatus](ctx, c.r, "inventory/{steamid}/status", mods...)
}

// PostInventoryBySteamIDRefresh — Refresh an inventory.
// Route: POST /inventory/{steamid}/refresh
func (c *Client) PostInventoryBySteamIDRefresh(ctx context.Context, mods ...aoni.RequestModifier) (*InventoryStatus, error) {
	return request.PostTo[InventoryStatus](ctx, c.r, "inventory/{steamid}/refresh", nil, mods...)
}

// DeleteClassifiedsAlertsByID — Delete alert
// Route: DELETE /classifieds/alerts/{id}
func (c *Client) DeleteClassifiedsAlertsByID(ctx context.Context, id string, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("id", id),
	}, mods...)

	resp, err := request.DeleteTo[map[string]any](ctx, c.r, "classifieds/alerts/{id}", nil, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetClassifiedsAlertsByID — Get alert
// Route: GET /classifieds/alerts/{id}
func (c *Client) GetClassifiedsAlertsByID(ctx context.Context, id string, mods ...aoni.RequestModifier) (map[string]any, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("id", id),
	}, mods...)

	resp, err := request.GetTo[map[string]any](ctx, c.r, "classifieds/alerts/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}
