// Code generated by oapi-gen-aoni. DO NOT EDIT.

package bptf

// Appid — Steam App ID.
type Appid int

// @aoni:dto casing=snake_case omitempty=true
type ClassifiedsResourceLimits struct {
	Listings map[string]any `json:"listings,omitempty"`
}

// CraftableEnum — Craftability identifier.
type CraftableEnum string

const (
	CraftableEnumCraftable    CraftableEnum = "Craftable"
	CraftableEnumNonCraftable CraftableEnum = "Non-Craftable"
	CraftableEnum1            CraftableEnum = "1"
	CraftableEnum0            CraftableEnum = "0"
	CraftableEnumTrue         CraftableEnum = "true"
	CraftableEnumFalse        CraftableEnum = "false"
)

// @aoni:dto casing=snake_case omitempty=true
type Currency struct {
	// if 1, then this currency should be used when rounding up     the currencies of an item. For example, the hat currency will have this value set to     0 because we do not want to price items in multiples of hats.
	Active int `json:"active,omitempty"`
	// Item craftability.
	Craftable string `json:"craftable,omitempty"`
	// defindex of the currency item
	Defindex int `json:"defindex,omitempty"`
	// Currency name.
	Name string `json:"name,omitempty"`
	// Plural form of the noun used for the suffix of the currency.
	Plural string         `json:"plural,omitempty"`
	Price  *V4pricesEntry `json:"price,omitempty"`
	//  The priceindex is an attribute that is applied to priced items that share the same definition index and quality. For most items, it is zero. Otherwise, the use varies by context:  Particle effects: The priceindex will correspond to the ID of the particle as documented in the Valve Web API.  Crates: The priceindex corresponds to the crate series.  Strangifiers/Unusualifiers: The priceindex of a Strangifier/Unusualifier corresponds to the definition index of the item it can be used on.  Chemistry Sets: The priceindex of a Chemistry Set is a hyphen-delimited string of two numbers; the definition index and the quality of the item. 1086-14 is the priceindex for a Collector's Festive Wrangler.
	Priceindex Priceindex `json:"priceindex,omitempty"`
	// Currency quality.
	Quality string `json:"quality,omitempty"`
	// Number of decimal places the price should be rounded to.
	Round int `json:"round,omitempty"`
	// Singular form of the noun used for the suffix of the currency.
	Single string `json:"single,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type Cursor struct {
	// Specified limit on returned documents.
	Limit int `json:"limit,omitempty"`
	// Specified cursor skip value.
	Skip int `json:"skip,omitempty"`
	// Total number of documents in this result set.
	Total int `json:"total,omitempty"`
}

// Entity — An item attribute that usually has an accompanying name, id, maybe a colour.
// @aoni:dto casing=snake_case omitempty=true
type Entity struct {
	// Hex colour value including the #.
	Color string `json:"color,omitempty"`
	// Property identifier.
	ID int `json:"id,omitempty"`
	// Property name.
	Name string `json:"name,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type ImpersonatedUser struct {
	// Avatar URL
	Avatar string `json:"avatar,omitempty"`
	// Persona name
	Personaname string `json:"personaname,omitempty"`
	// SteamID64
	Steamid string `json:"steamid,omitempty"`
}

// InventoryStatus — Inventory status
// @aoni:dto casing=snake_case omitempty=true
type InventoryStatus struct {
	// The UNIX timestamp of the server's current time.
	CurrentTime int `json:"current_time,omitempty"`
	// The UNIX timestamp of the last attempt to refresh the inventory. This value is used to gauge failures, as it does not guarantee an inventory was successfully updated (use the `timestamp` value for this). May be a very low number if the inventory has never been refreshed before.
	LastUpdate int `json:"last_update,omitempty"`
	// The UNIX timestamp of when the inventory may be refreshed again.
	NextUpdate int `json:"next_update,omitempty"`
	// The configured refresh interval for this inventory.
	RefreshInterval int `json:"refresh_interval,omitempty"`
	// The UNIX timestamp of the last successful attempt to refresh the inventory. May be a very low number if the inventory has never been refreshed before.
	Timestamp int `json:"timestamp,omitempty"`
}

// InventoryValues — Inventory values
// @aoni:dto casing=snake_case omitempty=true
type InventoryValues struct {
	// SCM market value for this inventory.
	MarketValue any `json:"market_value,omitempty"`
	// Community value for this inventory.
	Value any `json:"value,omitempty"`
}

// ItemDocument — The V2 item document, returned in listing responses and used as an input in various V2 APIs. If using in a request body, only certain fields are processed in order to validate the properties are genuine. This documentation only includes the fields supported for request inputs; the API will return other fields in the document, however we do not promise they won't be subject to change. The properties described here are highly likely to remain unchanged.
// @aoni:dto casing=snake_case omitempty=true
type ItemDocument struct {
	// Base item name.
	BaseName string `json:"baseName,omitempty"`
	// An item attribute that usually has an accompanying name, id, maybe a colour.
	ElevatedQuality *Entity `json:"elevatedQuality,omitempty"`
	// Image URL. This field is ignored in request bodies.
	ImageURL string `json:"imageUrl,omitempty"`
	// The 'full' item name, used as a SKU on backpack.tf (suggestions,, snapshots, etc.). This can include 'The' prefixes on non-special items. This field is ignored in request bodies.
	Name string `json:"name,omitempty"`
	// An item attribute that usually has an accompanying name, id, maybe a colour.
	Paint *Entity `json:"paint,omitempty"`
	// An item attribute that usually has an accompanying name, id, maybe a colour.
	Particle *Entity `json:"particle,omitempty"`
	// An item attribute that usually has an accompanying name, id, maybe a colour.
	Quality *Entity `json:"quality,omitempty"`
	// Item quantity. You can use this to specify how many items you would like to buy.
	Quantity int `json:"quantity,omitempty"`
	// An item attribute that usually has an accompanying name, id, maybe a colour.
	Rarity *Entity `json:"rarity,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type ItemResolvable struct {
	// Craftability identifier.
	Craftable CraftableEnum `json:"craftable,omitempty"`
	// Base item name.
	Item string `json:"item,omitempty"`
	//  The priceindex is an attribute that is applied to priced items that share the same definition index and quality. For most items, it is zero. Otherwise, the use varies by context:  Particle effects: The priceindex will correspond to the ID of the particle as documented in the Valve Web API.  Crates: The priceindex corresponds to the crate series.  Strangifiers/Unusualifiers: The priceindex of a Strangifier/Unusualifier corresponds to the definition index of the item it can be used on.  Chemistry Sets: The priceindex of a Chemistry Set is a hyphen-delimited string of two numbers; the definition index and the quality of the item. 1086-14 is the priceindex for a Collector's Festive Wrangler.
	Priceindex Priceindex `json:"priceindex,omitempty"`
	// Item quality. Can be an ID or a quality name.
	Quality string `json:"quality,omitempty"`
	// Tradability identifier.
	Tradable TradableEnum `json:"tradable,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type Listing struct {
	// Steam appid.
	Appid int `json:"appid,omitempty"`
	// UNIX timestamp of listing bump.
	BumpedAt string `json:"bumpedAt,omitempty"`
	// User only wants requests matching the buyout.
	BuyoutOnly bool `json:"buyoutOnly,omitempty"`
	// When listing fold is occurring, similar listings by a user are collapsed into one.
	Count int `json:"count,omitempty"`
	// A key-value map of currency IDs to values.
	Currencies ListingCurrencies `json:"currencies,omitempty"`
	// Listing details left by user.
	Details string `json:"details,omitempty"`
	// Listing ID.
	ID string `json:"id,omitempty"`
	// Listing intent.
	Intent ListingIntent `json:"intent,omitempty"`
	// The V2 item document, returned in listing responses and used as an input in various V2 APIs. If using in a request body, only certain fields are processed in order to validate the properties are genuine. This documentation only includes the fields supported for request inputs; the API will return other fields in the document, however we do not promise they won't be subject to change. The properties described here are highly likely to remain unchanged.
	Item *ItemDocument `json:"item,omitempty"`
	// UNIX timestamp of listing create.
	ListedAt string `json:"listedAt,omitempty"`
	// If this listing is promoted.
	Promoted bool `json:"promoted,omitempty"`
	// Listing creator steamid.
	Steamid string `json:"steamid,omitempty"`
	// User prefers trade offers.
	TradeOffersPreferred bool `json:"tradeOffersPreferred,omitempty"`
}

// ListingBatchCreateResult — A result object containing either a listing or an error.
// @aoni:dto casing=snake_case omitempty=true
type ListingBatchCreateResult struct {
	Error  *ResponseError `json:"error,omitempty"`
	Result *Listing       `json:"result,omitempty"`
}

// ListingCurrencies — A key-value map of currency IDs to values (keys, metal).
// @aoni:dto casing=snake_case omitempty=true
type ListingCurrencies struct {
	Keys  float64 `json:"keys,omitempty"`
	Metal float64 `json:"metal,omitempty"`
}

// ListingBatchUpdateItem represents a single item update in a batch PATCH request.
// @aoni:dto casing=snake_case omitempty=true
type ListingBatchUpdateItem struct {
	ID   string              `json:"id,omitempty"`
	Body ListingPatchRequest `json:"body,omitempty"`
}

// ListingBatchUpdateResponse represents the result of a batch PATCH operation.
// @aoni:dto casing=snake_case omitempty=true
type ListingBatchUpdateResponse struct {
	Updated []ListingBatchUpdatedEntry `json:"updated,omitempty"`
	Errors  []ListingBatchUpdateError  `json:"errors,omitempty"`
}

// ListingBatchUpdatedEntry contains the ID of a successfully updated listing.
// @aoni:dto casing=snake_case omitempty=true
type ListingBatchUpdatedEntry struct {
	ID string `json:"id,omitempty"`
}

// ListingBatchUpdateError contains error details for a failed listing update.
// @aoni:dto casing=snake_case omitempty=true
type ListingBatchUpdateError struct {
	ID      string `json:"id,omitempty"`
	Index   int    `json:"index,omitempty"`
	Message string `json:"message,omitempty"`
}

// ItemAttribute represents an attribute on a backpack.tf item.
// @aoni:dto casing=snake_case omitempty=true
type ItemAttribute struct {
	Defindex   int     `json:"defindex,omitempty"`
	Value      any     `json:"value,omitempty"`
	FloatValue float64 `json:"float_value,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type ListingDropRequest struct {
	// If specified, only drops listings with this intent.
	Intent string `json:"intent,omitempty"`
}

// ListingBatchDeleteRequest represents the request payload for batch deleting classified listings.
// @aoni:dto casing=snake_case omitempty=true
type ListingBatchDeleteRequest struct {
	ListingIDs []string `json:"listings,omitempty"`
}

// ListingIntent — Listing intent.
type ListingIntent string

const (
	ListingIntentBuy  ListingIntent = "buy"
	ListingIntentSell ListingIntent = "sell"
)

// ListingPatchRequest — Listing PATCH request body. If a field is not sent, no update will be performed for that field.
// @aoni:dto casing=snake_case omitempty=true
type ListingPatchRequest struct {
	// A key-value map of currency IDs to values.
	Currencies ListingCurrencies `json:"currencies,omitempty"`
	// New details for this listing.
	Details string `json:"details,omitempty"`
	// Item quantity. You can use this to specify how many items you would like to buy.
	Quantity int `json:"quantity,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type ListingResolvable struct {
	// A key-value map of currency IDs to values.
	Currencies ListingCurrencies `json:"currencies,omitempty"`
	// Listing details.
	Details string `json:"details,omitempty"`
	// Item ID corresponding to an item from the user's inventory. If this is set, this resolvable is assumed to be a sell listing.
	ID int `json:"id,omitempty"`
	// Accepts item inputs from the previous listing create APIs, but you are recommended to use the new itemDocument format for forwards compatibility. If this is set, this resolvable is assumed to be a buy listing.
	Item any `json:"item,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type ListingScrollable struct {
	Cursor  *Cursor   `json:"cursor,omitempty"`
	Results []Listing `json:"results,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type NotificationMarkState struct {
	// The number of updated notifications.
	Modified int `json:"modified,omitempty"`
}

// Priceindex —  The priceindex is an attribute that is applied to priced items that share the same definition index and quality. For most items, it is zero. Otherwise, the use varies by context:  Particle effects: The priceindex will correspond to the ID of the particle as documented in the Valve Web API.  Crates: The priceindex corresponds to the crate series.  Strangifiers/Unusualifiers: The priceindex of a Strangifier/Unusualifier corresponds to the definition index of the item it can be used on.  Chemistry Sets: The priceindex of a Chemistry Set is a hyphen-delimited string of two numbers; the definition index and the quality of the item. 1086-14 is the priceindex for a Collector's Festive Wrangler.
type Priceindex string

// @aoni:dto casing=snake_case omitempty=true
type ResponseError struct {
	// Verbose error message for humans.
	Message string `json:"message,omitempty"`
	// Error code for robots. Can be relied upon for some error handling.
	Reason string `json:"reason,omitempty"`
}

// SchemaItem — Schema item. Refer to Valve GetSchema documentation.
// @aoni:dto casing=snake_case omitempty=true
type SchemaItem struct {
}

// @aoni:dto casing=snake_case omitempty=true
type SpecialItemsResponse struct {
	Response map[string]any `json:"response,omitempty"`
}

// SuccessBoolProp — A success bool prop will be found on older APIs before we learned to use status codes to determine response success. They remain as a reminder of our failure.
type SuccessBoolProp int

// TradableEnum — Tradability identifier.
type TradableEnum string

const (
	TradableEnumTradable    TradableEnum = "Tradable"
	TradableEnumNonTradable TradableEnum = "Non-Tradable"
	TradableEnum1           TradableEnum = "1"
	TradableEnum0           TradableEnum = "0"
	TradableEnumTrue        TradableEnum = "true"
	TradableEnumFalse       TradableEnum = "false"
)

// UserAgentStatus — User agent status.
// @aoni:dto casing=snake_case omitempty=true
type UserAgentStatus struct {
	// If status is active, the name of the client.
	Client string `json:"client,omitempty"`
	// If status is active, the UNIX timestamp of the server's current time.
	CurrentTime int `json:"current_time,omitempty"`
	// If status is active, the UNIX timestamp for client expiry.
	ExpireAt int `json:"expire_at,omitempty"`
	// A string value representing the state of the agent.
	Status string `json:"status,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V1priceHistoryNode struct {
	// currency string.
	Currency string `json:"currency,omitempty"`
	// UNIX timestamp of price change.
	Timestamp int `json:"timestamp,omitempty"`
	// low-end of the price.
	Value float64 `json:"value,omitempty"`
	// high-end of the price.
	ValueHigh float64 `json:"value_high,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V1priceHistoryResponse struct {
	History []V1priceHistoryNode `json:"history,omitempty"`
	Success any                  `json:"success,omitempty"`
}

// V1user — user info doc
// @aoni:dto casing=snake_case omitempty=true
type V1user struct {
	Admin               string `json:"admin,omitempty"`
	Avatar              string `json:"avatar,omitempty"`
	Bans                string `json:"bans,omitempty"`
	Donated             string `json:"donated,omitempty"`
	Integrations        string `json:"integrations,omitempty"`
	Inventory           string `json:"inventory,omitempty"`
	LastOnline          string `json:"last_online,omitempty"`
	Name                string `json:"name,omitempty"`
	Premium             string `json:"premium,omitempty"`
	PremiumMonthsGifted int    `json:"premium_months_gifted,omitempty"`
	Trust               any    `json:"trust,omitempty"`
	Voting              any    `json:"voting,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V1userTrust struct {
	Negative int `json:"negative,omitempty"`
	Positive int `json:"positive,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V1userVoting struct {
}

// @aoni:dto casing=snake_case omitempty=true
type V4craftableDict struct {
	Craftable    V4priceindexDict `json:"Craftable,omitempty"`
	NonCraftable V4priceindexDict `json:"Non-Craftable,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V4priceindexDict struct {
}

// @aoni:dto casing=snake_case omitempty=true
type V4pricesBaseItemDoc struct {
	// An array of known defindexes for this item. Items may have more than one used defindex due to Valve shenanigans.
	Defindex []string `json:"defindex,omitempty"`
	// A dictionary of prices keyed by the quality integer.
	Prices map[string]V4tradableDict `json:"prices,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V4pricesEntry struct {
	// If set, item is an australium weapon.
	Australium int `json:"australium,omitempty"`
	// Internal currency name for the price
	Currency   string  `json:"currency,omitempty"`
	Difference float64 `json:"difference,omitempty"`
	LastUpdate int     `json:"last_update,omitempty"`
	// Value of the item, in the given currency
	Value float64 `json:"value,omitempty"`
	// Upper bound value for the item. Only set if the item has a price range.
	ValueHigh float64 `json:"value_high,omitempty"`
	// Item's value in the lowest currency without rounding. If raw is set to 2, this is the lower value if a high value exists. Otherwise, this is the average between the high and low value. Requires `raw`.
	ValueRaw     float64 `json:"value_raw,omitempty"`
	ValueRawHigh float64 `json:"value_raw_high,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V4pricesResponse struct {
	// The server time when the response was created.
	CurrentTime int `json:"current_time,omitempty"`
	// A dictionary of items keyed by the base item name.
	Items map[string]V4pricesBaseItemDoc `json:"items,omitempty"`
	// If success is 0, contains the reason for failure.
	Message string `json:"message,omitempty"`
	// The USD value of the smallest currency (i.e. Refined Metal).
	RawUsdValue int `json:"raw_usd_value,omitempty"`
	// A success bool prop will be found on older APIs before we learned to use status codes to determine response success. They remain as a reminder of our failure.
	Success SuccessBoolProp `json:"success,omitempty"`
	// The name of the smallest currency as it appears in the priceindex objects.
	UsdCurrency string `json:"usd_currency,omitempty"`
	// The definition index of the USD currency.
	UsdCurrencyIndex int `json:"usd_currency_index,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V4tradableDict struct {
	NonTradable *V4craftableDict `json:"Non-Tradable,omitempty"`
	Tradable    *V4craftableDict `json:"Tradable,omitempty"`
}
