// Code generated by aoni-gen. DO NOT EDIT.

package bptf

import (
	"fmt"
	"net/url"
	"strconv"
)

// AppendFormData serializes ClassifiedsResourceLimits into url-encoded form bytes on dst buffer (0 B/op).
func (r *ClassifiedsResourceLimits) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	return dst
}

// AppendQuery serializes ClassifiedsResourceLimits into query string bytes on dst buffer (0 B/op).
func (r *ClassifiedsResourceLimits) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ClassifiedsResourceLimits into url.Values without reflection.
func (r *ClassifiedsResourceLimits) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
}

// AppendFormData serializes Currency into url-encoded form bytes on dst buffer (0 B/op).
func (r *Currency) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Active != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "active="...)
		dst = strconv.AppendInt(dst, int64(r.Active), 10)
	}
	if r.Craftable != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "craftable="...)
		dst = append(dst, url.QueryEscape(r.Craftable)...)
	}
	if r.Defindex != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "defindex="...)
		dst = strconv.AppendInt(dst, int64(r.Defindex), 10)
	}
	if r.Name != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "name="...)
		dst = append(dst, url.QueryEscape(r.Name)...)
	}
	if r.Plural != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "plural="...)
		dst = append(dst, url.QueryEscape(r.Plural)...)
	}
	if r.Price != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "price="...)
		dst = append(dst, fmt.Sprint(r.Price)...)
	}
	if strVal := fmt.Sprint(r.Priceindex); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "priceindex="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Quality != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "quality="...)
		dst = append(dst, url.QueryEscape(r.Quality)...)
	}
	if r.Round != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "round="...)
		dst = strconv.AppendInt(dst, int64(r.Round), 10)
	}
	if r.Single != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "single="...)
		dst = append(dst, url.QueryEscape(r.Single)...)
	}

	return dst
}

// AppendQuery serializes Currency into query string bytes on dst buffer (0 B/op).
func (r *Currency) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes Currency into url.Values without reflection.
func (r *Currency) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Active != 0 {
		vals.Set("active", strconv.FormatInt(int64(r.Active), 10))
	}
	if r.Craftable != "" {
		vals.Set("craftable", r.Craftable)
	}
	if r.Defindex != 0 {
		vals.Set("defindex", strconv.FormatInt(int64(r.Defindex), 10))
	}
	if r.Name != "" {
		vals.Set("name", r.Name)
	}
	if r.Plural != "" {
		vals.Set("plural", r.Plural)
	}
	if r.Price != nil {
		vals.Set("price", fmt.Sprint(r.Price))
	}
	if strVal := fmt.Sprint(r.Priceindex); strVal != "" && strVal != "0" {
		vals.Set("priceindex", strVal)
	}
	if r.Quality != "" {
		vals.Set("quality", r.Quality)
	}
	if r.Round != 0 {
		vals.Set("round", strconv.FormatInt(int64(r.Round), 10))
	}
	if r.Single != "" {
		vals.Set("single", r.Single)
	}
}

// AppendFormData serializes Cursor into url-encoded form bytes on dst buffer (0 B/op).
func (r *Cursor) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Limit != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "limit="...)
		dst = strconv.AppendInt(dst, int64(r.Limit), 10)
	}
	if r.Skip != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "skip="...)
		dst = strconv.AppendInt(dst, int64(r.Skip), 10)
	}
	if r.Total != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "total="...)
		dst = strconv.AppendInt(dst, int64(r.Total), 10)
	}

	return dst
}

// AppendQuery serializes Cursor into query string bytes on dst buffer (0 B/op).
func (r *Cursor) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes Cursor into url.Values without reflection.
func (r *Cursor) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Limit != 0 {
		vals.Set("limit", strconv.FormatInt(int64(r.Limit), 10))
	}
	if r.Skip != 0 {
		vals.Set("skip", strconv.FormatInt(int64(r.Skip), 10))
	}
	if r.Total != 0 {
		vals.Set("total", strconv.FormatInt(int64(r.Total), 10))
	}
}

// AppendFormData serializes Entity into url-encoded form bytes on dst buffer (0 B/op).
func (r *Entity) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Color != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "color="...)
		dst = append(dst, url.QueryEscape(r.Color)...)
	}
	if r.ID != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "id="...)
		dst = strconv.AppendInt(dst, int64(r.ID), 10)
	}
	if r.Name != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "name="...)
		dst = append(dst, url.QueryEscape(r.Name)...)
	}

	return dst
}

// AppendQuery serializes Entity into query string bytes on dst buffer (0 B/op).
func (r *Entity) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes Entity into url.Values without reflection.
func (r *Entity) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Color != "" {
		vals.Set("color", r.Color)
	}
	if r.ID != 0 {
		vals.Set("id", strconv.FormatInt(int64(r.ID), 10))
	}
	if r.Name != "" {
		vals.Set("name", r.Name)
	}
}

// AppendFormData serializes ImpersonatedUser into url-encoded form bytes on dst buffer (0 B/op).
func (r *ImpersonatedUser) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Avatar != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "avatar="...)
		dst = append(dst, url.QueryEscape(r.Avatar)...)
	}
	if r.Personaname != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "personaname="...)
		dst = append(dst, url.QueryEscape(r.Personaname)...)
	}
	if r.Steamid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "steamid="...)
		dst = append(dst, url.QueryEscape(r.Steamid)...)
	}

	return dst
}

// AppendQuery serializes ImpersonatedUser into query string bytes on dst buffer (0 B/op).
func (r *ImpersonatedUser) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ImpersonatedUser into url.Values without reflection.
func (r *ImpersonatedUser) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Avatar != "" {
		vals.Set("avatar", r.Avatar)
	}
	if r.Personaname != "" {
		vals.Set("personaname", r.Personaname)
	}
	if r.Steamid != "" {
		vals.Set("steamid", r.Steamid)
	}
}

// AppendFormData serializes InventoryStatus into url-encoded form bytes on dst buffer (0 B/op).
func (r *InventoryStatus) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.CurrentTime != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "current_time="...)
		dst = strconv.AppendInt(dst, int64(r.CurrentTime), 10)
	}
	if r.LastUpdate != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "last_update="...)
		dst = strconv.AppendInt(dst, int64(r.LastUpdate), 10)
	}
	if r.NextUpdate != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "next_update="...)
		dst = strconv.AppendInt(dst, int64(r.NextUpdate), 10)
	}
	if r.RefreshInterval != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "refresh_interval="...)
		dst = strconv.AppendInt(dst, int64(r.RefreshInterval), 10)
	}
	if r.Timestamp != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "timestamp="...)
		dst = strconv.AppendInt(dst, int64(r.Timestamp), 10)
	}

	return dst
}

// AppendQuery serializes InventoryStatus into query string bytes on dst buffer (0 B/op).
func (r *InventoryStatus) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes InventoryStatus into url.Values without reflection.
func (r *InventoryStatus) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.CurrentTime != 0 {
		vals.Set("current_time", strconv.FormatInt(int64(r.CurrentTime), 10))
	}
	if r.LastUpdate != 0 {
		vals.Set("last_update", strconv.FormatInt(int64(r.LastUpdate), 10))
	}
	if r.NextUpdate != 0 {
		vals.Set("next_update", strconv.FormatInt(int64(r.NextUpdate), 10))
	}
	if r.RefreshInterval != 0 {
		vals.Set("refresh_interval", strconv.FormatInt(int64(r.RefreshInterval), 10))
	}
	if r.Timestamp != 0 {
		vals.Set("timestamp", strconv.FormatInt(int64(r.Timestamp), 10))
	}
}

// AppendFormData serializes InventoryValues into url-encoded form bytes on dst buffer (0 B/op).
func (r *InventoryValues) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.MarketValue != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "market_value="...)
		dst = append(dst, fmt.Sprint(r.MarketValue)...)
	}
	if r.Value != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "value="...)
		dst = append(dst, fmt.Sprint(r.Value)...)
	}

	return dst
}

// AppendQuery serializes InventoryValues into query string bytes on dst buffer (0 B/op).
func (r *InventoryValues) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes InventoryValues into url.Values without reflection.
func (r *InventoryValues) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.MarketValue != nil {
		vals.Set("market_value", fmt.Sprint(r.MarketValue))
	}
	if r.Value != nil {
		vals.Set("value", fmt.Sprint(r.Value))
	}
}

// AppendFormData serializes ItemDocument into url-encoded form bytes on dst buffer (0 B/op).
func (r *ItemDocument) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.BaseName != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "baseName="...)
		dst = append(dst, url.QueryEscape(r.BaseName)...)
	}
	if r.ElevatedQuality != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "elevatedQuality="...)
		dst = append(dst, fmt.Sprint(r.ElevatedQuality)...)
	}
	if r.ImageURL != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "imageUrl="...)
		dst = append(dst, url.QueryEscape(r.ImageURL)...)
	}
	if r.Name != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "name="...)
		dst = append(dst, url.QueryEscape(r.Name)...)
	}
	if r.Paint != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "paint="...)
		dst = append(dst, fmt.Sprint(r.Paint)...)
	}
	if r.Particle != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "particle="...)
		dst = append(dst, fmt.Sprint(r.Particle)...)
	}
	if r.Quality != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "quality="...)
		dst = append(dst, fmt.Sprint(r.Quality)...)
	}
	if r.Quantity != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "quantity="...)
		dst = strconv.AppendInt(dst, int64(r.Quantity), 10)
	}
	if r.Rarity != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "rarity="...)
		dst = append(dst, fmt.Sprint(r.Rarity)...)
	}

	return dst
}

// AppendQuery serializes ItemDocument into query string bytes on dst buffer (0 B/op).
func (r *ItemDocument) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ItemDocument into url.Values without reflection.
func (r *ItemDocument) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.BaseName != "" {
		vals.Set("baseName", r.BaseName)
	}
	if r.ElevatedQuality != nil {
		vals.Set("elevatedQuality", fmt.Sprint(r.ElevatedQuality))
	}
	if r.ImageURL != "" {
		vals.Set("imageUrl", r.ImageURL)
	}
	if r.Name != "" {
		vals.Set("name", r.Name)
	}
	if r.Paint != nil {
		vals.Set("paint", fmt.Sprint(r.Paint))
	}
	if r.Particle != nil {
		vals.Set("particle", fmt.Sprint(r.Particle))
	}
	if r.Quality != nil {
		vals.Set("quality", fmt.Sprint(r.Quality))
	}
	if r.Quantity != 0 {
		vals.Set("quantity", strconv.FormatInt(int64(r.Quantity), 10))
	}
	if r.Rarity != nil {
		vals.Set("rarity", fmt.Sprint(r.Rarity))
	}
}

// AppendFormData serializes ItemResolvable into url-encoded form bytes on dst buffer (0 B/op).
func (r *ItemResolvable) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if strVal := fmt.Sprint(r.Craftable); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "craftable="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Item != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "item="...)
		dst = append(dst, url.QueryEscape(r.Item)...)
	}
	if strVal := fmt.Sprint(r.Priceindex); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "priceindex="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Quality != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "quality="...)
		dst = append(dst, url.QueryEscape(r.Quality)...)
	}
	if strVal := fmt.Sprint(r.Tradable); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "tradable="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}

	return dst
}

// AppendQuery serializes ItemResolvable into query string bytes on dst buffer (0 B/op).
func (r *ItemResolvable) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ItemResolvable into url.Values without reflection.
func (r *ItemResolvable) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if strVal := fmt.Sprint(r.Craftable); strVal != "" && strVal != "0" {
		vals.Set("craftable", strVal)
	}
	if r.Item != "" {
		vals.Set("item", r.Item)
	}
	if strVal := fmt.Sprint(r.Priceindex); strVal != "" && strVal != "0" {
		vals.Set("priceindex", strVal)
	}
	if r.Quality != "" {
		vals.Set("quality", r.Quality)
	}
	if strVal := fmt.Sprint(r.Tradable); strVal != "" && strVal != "0" {
		vals.Set("tradable", strVal)
	}
}

// AppendFormData serializes Listing into url-encoded form bytes on dst buffer (0 B/op).
func (r *Listing) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Appid != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "appid="...)
		dst = strconv.AppendInt(dst, int64(r.Appid), 10)
	}
	if r.BumpedAt != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "bumpedAt="...)
		dst = append(dst, url.QueryEscape(r.BumpedAt)...)
	}
	if r.BuyoutOnly {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "buyoutOnly=true"...)
	}
	if r.Count != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "count="...)
		dst = strconv.AppendInt(dst, int64(r.Count), 10)
	}
	if strVal := fmt.Sprint(r.Currencies); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "currencies="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Details != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "details="...)
		dst = append(dst, url.QueryEscape(r.Details)...)
	}
	if r.ID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "id="...)
		dst = append(dst, url.QueryEscape(r.ID)...)
	}
	if strVal := fmt.Sprint(r.Intent); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "intent="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Item != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "item="...)
		dst = append(dst, fmt.Sprint(r.Item)...)
	}
	if r.ListedAt != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "listedAt="...)
		dst = append(dst, url.QueryEscape(r.ListedAt)...)
	}
	if r.Promoted {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "promoted=true"...)
	}
	if r.Steamid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "steamid="...)
		dst = append(dst, url.QueryEscape(r.Steamid)...)
	}
	if r.TradeOffersPreferred {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "tradeOffersPreferred=true"...)
	}

	return dst
}

// AppendQuery serializes Listing into query string bytes on dst buffer (0 B/op).
func (r *Listing) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes Listing into url.Values without reflection.
func (r *Listing) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Appid != 0 {
		vals.Set("appid", strconv.FormatInt(int64(r.Appid), 10))
	}
	if r.BumpedAt != "" {
		vals.Set("bumpedAt", r.BumpedAt)
	}
	if r.BuyoutOnly {
		vals.Set("buyoutOnly", "true")
	}
	if r.Count != 0 {
		vals.Set("count", strconv.FormatInt(int64(r.Count), 10))
	}
	if strVal := fmt.Sprint(r.Currencies); strVal != "" && strVal != "0" {
		vals.Set("currencies", strVal)
	}
	if r.Details != "" {
		vals.Set("details", r.Details)
	}
	if r.ID != "" {
		vals.Set("id", r.ID)
	}
	if strVal := fmt.Sprint(r.Intent); strVal != "" && strVal != "0" {
		vals.Set("intent", strVal)
	}
	if r.Item != nil {
		vals.Set("item", fmt.Sprint(r.Item))
	}
	if r.ListedAt != "" {
		vals.Set("listedAt", r.ListedAt)
	}
	if r.Promoted {
		vals.Set("promoted", "true")
	}
	if r.Steamid != "" {
		vals.Set("steamid", r.Steamid)
	}
	if r.TradeOffersPreferred {
		vals.Set("tradeOffersPreferred", "true")
	}
}

// AppendFormData serializes ListingBatchCreateResult into url-encoded form bytes on dst buffer (0 B/op).
func (r *ListingBatchCreateResult) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Error != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "error="...)
		dst = append(dst, fmt.Sprint(r.Error)...)
	}
	if r.Result != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "result="...)
		dst = append(dst, fmt.Sprint(r.Result)...)
	}

	return dst
}

// AppendQuery serializes ListingBatchCreateResult into query string bytes on dst buffer (0 B/op).
func (r *ListingBatchCreateResult) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ListingBatchCreateResult into url.Values without reflection.
func (r *ListingBatchCreateResult) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Error != nil {
		vals.Set("error", fmt.Sprint(r.Error))
	}
	if r.Result != nil {
		vals.Set("result", fmt.Sprint(r.Result))
	}
}

// AppendFormData serializes ListingCurrencies into url-encoded form bytes on dst buffer (0 B/op).
func (r *ListingCurrencies) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	return dst
}

// AppendQuery serializes ListingCurrencies into query string bytes on dst buffer (0 B/op).
func (r *ListingCurrencies) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ListingCurrencies into url.Values without reflection.
func (r *ListingCurrencies) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
}

// AppendFormData serializes ListingDropRequest into url-encoded form bytes on dst buffer (0 B/op).
func (r *ListingDropRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Intent != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "intent="...)
		dst = append(dst, url.QueryEscape(r.Intent)...)
	}

	return dst
}

// AppendQuery serializes ListingDropRequest into query string bytes on dst buffer (0 B/op).
func (r *ListingDropRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ListingDropRequest into url.Values without reflection.
func (r *ListingDropRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Intent != "" {
		vals.Set("intent", r.Intent)
	}
}

// AppendFormData serializes ListingPatchRequest into url-encoded form bytes on dst buffer (0 B/op).
func (r *ListingPatchRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if strVal := fmt.Sprint(r.Currencies); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "currencies="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Details != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "details="...)
		dst = append(dst, url.QueryEscape(r.Details)...)
	}
	if r.Quantity != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "quantity="...)
		dst = strconv.AppendInt(dst, int64(r.Quantity), 10)
	}

	return dst
}

// AppendQuery serializes ListingPatchRequest into query string bytes on dst buffer (0 B/op).
func (r *ListingPatchRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ListingPatchRequest into url.Values without reflection.
func (r *ListingPatchRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if strVal := fmt.Sprint(r.Currencies); strVal != "" && strVal != "0" {
		vals.Set("currencies", strVal)
	}
	if r.Details != "" {
		vals.Set("details", r.Details)
	}
	if r.Quantity != 0 {
		vals.Set("quantity", strconv.FormatInt(int64(r.Quantity), 10))
	}
}

// AppendFormData serializes ListingResolvable into url-encoded form bytes on dst buffer (0 B/op).
func (r *ListingResolvable) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if strVal := fmt.Sprint(r.Currencies); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "currencies="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Details != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "details="...)
		dst = append(dst, url.QueryEscape(r.Details)...)
	}
	if r.ID != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "id="...)
		dst = strconv.AppendInt(dst, int64(r.ID), 10)
	}
	if r.Item != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "item="...)
		dst = append(dst, fmt.Sprint(r.Item)...)
	}

	return dst
}

// AppendQuery serializes ListingResolvable into query string bytes on dst buffer (0 B/op).
func (r *ListingResolvable) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ListingResolvable into url.Values without reflection.
func (r *ListingResolvable) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if strVal := fmt.Sprint(r.Currencies); strVal != "" && strVal != "0" {
		vals.Set("currencies", strVal)
	}
	if r.Details != "" {
		vals.Set("details", r.Details)
	}
	if r.ID != 0 {
		vals.Set("id", strconv.FormatInt(int64(r.ID), 10))
	}
	if r.Item != nil {
		vals.Set("item", fmt.Sprint(r.Item))
	}
}

// AppendFormData serializes ListingScrollable into url-encoded form bytes on dst buffer (0 B/op).
func (r *ListingScrollable) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Cursor != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "cursor="...)
		dst = append(dst, fmt.Sprint(r.Cursor)...)
	}

	return dst
}

// AppendQuery serializes ListingScrollable into query string bytes on dst buffer (0 B/op).
func (r *ListingScrollable) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ListingScrollable into url.Values without reflection.
func (r *ListingScrollable) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Cursor != nil {
		vals.Set("cursor", fmt.Sprint(r.Cursor))
	}
}

// AppendFormData serializes NotificationMarkState into url-encoded form bytes on dst buffer (0 B/op).
func (r *NotificationMarkState) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Modified != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "modified="...)
		dst = strconv.AppendInt(dst, int64(r.Modified), 10)
	}

	return dst
}

// AppendQuery serializes NotificationMarkState into query string bytes on dst buffer (0 B/op).
func (r *NotificationMarkState) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes NotificationMarkState into url.Values without reflection.
func (r *NotificationMarkState) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Modified != 0 {
		vals.Set("modified", strconv.FormatInt(int64(r.Modified), 10))
	}
}

// AppendFormData serializes ResponseError into url-encoded form bytes on dst buffer (0 B/op).
func (r *ResponseError) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Message != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "message="...)
		dst = append(dst, url.QueryEscape(r.Message)...)
	}
	if r.Reason != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "reason="...)
		dst = append(dst, url.QueryEscape(r.Reason)...)
	}

	return dst
}

// AppendQuery serializes ResponseError into query string bytes on dst buffer (0 B/op).
func (r *ResponseError) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ResponseError into url.Values without reflection.
func (r *ResponseError) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Message != "" {
		vals.Set("message", r.Message)
	}
	if r.Reason != "" {
		vals.Set("reason", r.Reason)
	}
}

// AppendFormData serializes SchemaItem into url-encoded form bytes on dst buffer (0 B/op).
func (r *SchemaItem) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	return dst
}

// AppendQuery serializes SchemaItem into query string bytes on dst buffer (0 B/op).
func (r *SchemaItem) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes SchemaItem into url.Values without reflection.
func (r *SchemaItem) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
}

// AppendFormData serializes SpecialItemsResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *SpecialItemsResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	return dst
}

// AppendQuery serializes SpecialItemsResponse into query string bytes on dst buffer (0 B/op).
func (r *SpecialItemsResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes SpecialItemsResponse into url.Values without reflection.
func (r *SpecialItemsResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
}

// AppendFormData serializes UserAgentStatus into url-encoded form bytes on dst buffer (0 B/op).
func (r *UserAgentStatus) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Client != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "client="...)
		dst = append(dst, url.QueryEscape(r.Client)...)
	}
	if r.CurrentTime != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "current_time="...)
		dst = strconv.AppendInt(dst, int64(r.CurrentTime), 10)
	}
	if r.ExpireAt != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "expire_at="...)
		dst = strconv.AppendInt(dst, int64(r.ExpireAt), 10)
	}
	if r.Status != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "status="...)
		dst = append(dst, url.QueryEscape(r.Status)...)
	}

	return dst
}

// AppendQuery serializes UserAgentStatus into query string bytes on dst buffer (0 B/op).
func (r *UserAgentStatus) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes UserAgentStatus into url.Values without reflection.
func (r *UserAgentStatus) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Client != "" {
		vals.Set("client", r.Client)
	}
	if r.CurrentTime != 0 {
		vals.Set("current_time", strconv.FormatInt(int64(r.CurrentTime), 10))
	}
	if r.ExpireAt != 0 {
		vals.Set("expire_at", strconv.FormatInt(int64(r.ExpireAt), 10))
	}
	if r.Status != "" {
		vals.Set("status", r.Status)
	}
}

// AppendFormData serializes V1priceHistoryNode into url-encoded form bytes on dst buffer (0 B/op).
func (r *V1priceHistoryNode) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Currency != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "currency="...)
		dst = append(dst, url.QueryEscape(r.Currency)...)
	}
	if r.Timestamp != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "timestamp="...)
		dst = strconv.AppendInt(dst, int64(r.Timestamp), 10)
	}
	if r.Value != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "value="...)
		dst = strconv.AppendFloat(dst, float64(r.Value), 'f', -1, 64)
	}
	if r.ValueHigh != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "value_high="...)
		dst = strconv.AppendFloat(dst, float64(r.ValueHigh), 'f', -1, 64)
	}

	return dst
}

// AppendQuery serializes V1priceHistoryNode into query string bytes on dst buffer (0 B/op).
func (r *V1priceHistoryNode) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V1priceHistoryNode into url.Values without reflection.
func (r *V1priceHistoryNode) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Currency != "" {
		vals.Set("currency", r.Currency)
	}
	if r.Timestamp != 0 {
		vals.Set("timestamp", strconv.FormatInt(int64(r.Timestamp), 10))
	}
	if r.Value != 0 {
		vals.Set("value", strconv.FormatFloat(float64(r.Value), 'f', -1, 64))
	}
	if r.ValueHigh != 0 {
		vals.Set("value_high", strconv.FormatFloat(float64(r.ValueHigh), 'f', -1, 64))
	}
}

// AppendFormData serializes V1priceHistoryResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *V1priceHistoryResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Success != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success="...)
		dst = append(dst, fmt.Sprint(r.Success)...)
	}

	return dst
}

// AppendQuery serializes V1priceHistoryResponse into query string bytes on dst buffer (0 B/op).
func (r *V1priceHistoryResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V1priceHistoryResponse into url.Values without reflection.
func (r *V1priceHistoryResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Success != nil {
		vals.Set("success", fmt.Sprint(r.Success))
	}
}

// AppendFormData serializes V1user into url-encoded form bytes on dst buffer (0 B/op).
func (r *V1user) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Admin != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "admin="...)
		dst = append(dst, url.QueryEscape(r.Admin)...)
	}
	if r.Avatar != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "avatar="...)
		dst = append(dst, url.QueryEscape(r.Avatar)...)
	}
	if r.Bans != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "bans="...)
		dst = append(dst, url.QueryEscape(r.Bans)...)
	}
	if r.Donated != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "donated="...)
		dst = append(dst, url.QueryEscape(r.Donated)...)
	}
	if r.Integrations != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "integrations="...)
		dst = append(dst, url.QueryEscape(r.Integrations)...)
	}
	if r.Inventory != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "inventory="...)
		dst = append(dst, url.QueryEscape(r.Inventory)...)
	}
	if r.LastOnline != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "last_online="...)
		dst = append(dst, url.QueryEscape(r.LastOnline)...)
	}
	if r.Name != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "name="...)
		dst = append(dst, url.QueryEscape(r.Name)...)
	}
	if r.Premium != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "premium="...)
		dst = append(dst, url.QueryEscape(r.Premium)...)
	}
	if r.PremiumMonthsGifted != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "premium_months_gifted="...)
		dst = strconv.AppendInt(dst, int64(r.PremiumMonthsGifted), 10)
	}
	if r.Trust != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "trust="...)
		dst = append(dst, fmt.Sprint(r.Trust)...)
	}
	if r.Voting != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "voting="...)
		dst = append(dst, fmt.Sprint(r.Voting)...)
	}

	return dst
}

// AppendQuery serializes V1user into query string bytes on dst buffer (0 B/op).
func (r *V1user) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V1user into url.Values without reflection.
func (r *V1user) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Admin != "" {
		vals.Set("admin", r.Admin)
	}
	if r.Avatar != "" {
		vals.Set("avatar", r.Avatar)
	}
	if r.Bans != "" {
		vals.Set("bans", r.Bans)
	}
	if r.Donated != "" {
		vals.Set("donated", r.Donated)
	}
	if r.Integrations != "" {
		vals.Set("integrations", r.Integrations)
	}
	if r.Inventory != "" {
		vals.Set("inventory", r.Inventory)
	}
	if r.LastOnline != "" {
		vals.Set("last_online", r.LastOnline)
	}
	if r.Name != "" {
		vals.Set("name", r.Name)
	}
	if r.Premium != "" {
		vals.Set("premium", r.Premium)
	}
	if r.PremiumMonthsGifted != 0 {
		vals.Set("premium_months_gifted", strconv.FormatInt(int64(r.PremiumMonthsGifted), 10))
	}
	if r.Trust != nil {
		vals.Set("trust", fmt.Sprint(r.Trust))
	}
	if r.Voting != nil {
		vals.Set("voting", fmt.Sprint(r.Voting))
	}
}

// AppendFormData serializes V1userTrust into url-encoded form bytes on dst buffer (0 B/op).
func (r *V1userTrust) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Negative != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "negative="...)
		dst = strconv.AppendInt(dst, int64(r.Negative), 10)
	}
	if r.Positive != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "positive="...)
		dst = strconv.AppendInt(dst, int64(r.Positive), 10)
	}

	return dst
}

// AppendQuery serializes V1userTrust into query string bytes on dst buffer (0 B/op).
func (r *V1userTrust) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V1userTrust into url.Values without reflection.
func (r *V1userTrust) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Negative != 0 {
		vals.Set("negative", strconv.FormatInt(int64(r.Negative), 10))
	}
	if r.Positive != 0 {
		vals.Set("positive", strconv.FormatInt(int64(r.Positive), 10))
	}
}

// AppendFormData serializes V1userVoting into url-encoded form bytes on dst buffer (0 B/op).
func (r *V1userVoting) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	return dst
}

// AppendQuery serializes V1userVoting into query string bytes on dst buffer (0 B/op).
func (r *V1userVoting) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V1userVoting into url.Values without reflection.
func (r *V1userVoting) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
}

// AppendFormData serializes V4craftableDict into url-encoded form bytes on dst buffer (0 B/op).
func (r *V4craftableDict) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if strVal := fmt.Sprint(r.Craftable); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "Craftable="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if strVal := fmt.Sprint(r.NonCraftable); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "Non-Craftable="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}

	return dst
}

// AppendQuery serializes V4craftableDict into query string bytes on dst buffer (0 B/op).
func (r *V4craftableDict) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V4craftableDict into url.Values without reflection.
func (r *V4craftableDict) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if strVal := fmt.Sprint(r.Craftable); strVal != "" && strVal != "0" {
		vals.Set("Craftable", strVal)
	}
	if strVal := fmt.Sprint(r.NonCraftable); strVal != "" && strVal != "0" {
		vals.Set("Non-Craftable", strVal)
	}
}

// AppendFormData serializes V4priceindexDict into url-encoded form bytes on dst buffer (0 B/op).
func (r *V4priceindexDict) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	return dst
}

// AppendQuery serializes V4priceindexDict into query string bytes on dst buffer (0 B/op).
func (r *V4priceindexDict) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V4priceindexDict into url.Values without reflection.
func (r *V4priceindexDict) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
}

// AppendFormData serializes V4pricesBaseItemDoc into url-encoded form bytes on dst buffer (0 B/op).
func (r *V4pricesBaseItemDoc) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	for _, v := range r.Defindex {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "defindex="...)
		dst = append(dst, url.QueryEscape(v)...)
	}

	return dst
}

// AppendQuery serializes V4pricesBaseItemDoc into query string bytes on dst buffer (0 B/op).
func (r *V4pricesBaseItemDoc) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V4pricesBaseItemDoc into url.Values without reflection.
func (r *V4pricesBaseItemDoc) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	for _, v := range r.Defindex {
		vals.Add("defindex", v)
	}
}

// AppendFormData serializes V4pricesEntry into url-encoded form bytes on dst buffer (0 B/op).
func (r *V4pricesEntry) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Australium != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "australium="...)
		dst = strconv.AppendInt(dst, int64(r.Australium), 10)
	}
	if r.Currency != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "currency="...)
		dst = append(dst, url.QueryEscape(r.Currency)...)
	}
	if r.Difference != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "difference="...)
		dst = strconv.AppendFloat(dst, float64(r.Difference), 'f', -1, 64)
	}
	if r.LastUpdate != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "last_update="...)
		dst = strconv.AppendInt(dst, int64(r.LastUpdate), 10)
	}
	if r.Value != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "value="...)
		dst = strconv.AppendFloat(dst, float64(r.Value), 'f', -1, 64)
	}
	if r.ValueHigh != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "value_high="...)
		dst = strconv.AppendFloat(dst, float64(r.ValueHigh), 'f', -1, 64)
	}
	if r.ValueRaw != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "value_raw="...)
		dst = strconv.AppendFloat(dst, float64(r.ValueRaw), 'f', -1, 64)
	}
	if r.ValueRawHigh != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "value_raw_high="...)
		dst = strconv.AppendFloat(dst, float64(r.ValueRawHigh), 'f', -1, 64)
	}

	return dst
}

// AppendQuery serializes V4pricesEntry into query string bytes on dst buffer (0 B/op).
func (r *V4pricesEntry) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V4pricesEntry into url.Values without reflection.
func (r *V4pricesEntry) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Australium != 0 {
		vals.Set("australium", strconv.FormatInt(int64(r.Australium), 10))
	}
	if r.Currency != "" {
		vals.Set("currency", r.Currency)
	}
	if r.Difference != 0 {
		vals.Set("difference", strconv.FormatFloat(float64(r.Difference), 'f', -1, 64))
	}
	if r.LastUpdate != 0 {
		vals.Set("last_update", strconv.FormatInt(int64(r.LastUpdate), 10))
	}
	if r.Value != 0 {
		vals.Set("value", strconv.FormatFloat(float64(r.Value), 'f', -1, 64))
	}
	if r.ValueHigh != 0 {
		vals.Set("value_high", strconv.FormatFloat(float64(r.ValueHigh), 'f', -1, 64))
	}
	if r.ValueRaw != 0 {
		vals.Set("value_raw", strconv.FormatFloat(float64(r.ValueRaw), 'f', -1, 64))
	}
	if r.ValueRawHigh != 0 {
		vals.Set("value_raw_high", strconv.FormatFloat(float64(r.ValueRawHigh), 'f', -1, 64))
	}
}

// AppendFormData serializes V4pricesResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *V4pricesResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.CurrentTime != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "current_time="...)
		dst = strconv.AppendInt(dst, int64(r.CurrentTime), 10)
	}
	if r.Message != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "message="...)
		dst = append(dst, url.QueryEscape(r.Message)...)
	}
	if r.RawUsdValue != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "raw_usd_value="...)
		dst = strconv.AppendInt(dst, int64(r.RawUsdValue), 10)
	}
	if strVal := fmt.Sprint(r.Success); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.UsdCurrency != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "usd_currency="...)
		dst = append(dst, url.QueryEscape(r.UsdCurrency)...)
	}
	if r.UsdCurrencyIndex != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "usd_currency_index="...)
		dst = strconv.AppendInt(dst, int64(r.UsdCurrencyIndex), 10)
	}

	return dst
}

// AppendQuery serializes V4pricesResponse into query string bytes on dst buffer (0 B/op).
func (r *V4pricesResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V4pricesResponse into url.Values without reflection.
func (r *V4pricesResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.CurrentTime != 0 {
		vals.Set("current_time", strconv.FormatInt(int64(r.CurrentTime), 10))
	}
	if r.Message != "" {
		vals.Set("message", r.Message)
	}
	if r.RawUsdValue != 0 {
		vals.Set("raw_usd_value", strconv.FormatInt(int64(r.RawUsdValue), 10))
	}
	if strVal := fmt.Sprint(r.Success); strVal != "" && strVal != "0" {
		vals.Set("success", strVal)
	}
	if r.UsdCurrency != "" {
		vals.Set("usd_currency", r.UsdCurrency)
	}
	if r.UsdCurrencyIndex != 0 {
		vals.Set("usd_currency_index", strconv.FormatInt(int64(r.UsdCurrencyIndex), 10))
	}
}

// AppendFormData serializes V4tradableDict into url-encoded form bytes on dst buffer (0 B/op).
func (r *V4tradableDict) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.NonTradable != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "Non-Tradable="...)
		dst = append(dst, fmt.Sprint(r.NonTradable)...)
	}
	if r.Tradable != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "Tradable="...)
		dst = append(dst, fmt.Sprint(r.Tradable)...)
	}

	return dst
}

// AppendQuery serializes V4tradableDict into query string bytes on dst buffer (0 B/op).
func (r *V4tradableDict) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V4tradableDict into url.Values without reflection.
func (r *V4tradableDict) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.NonTradable != nil {
		vals.Set("Non-Tradable", fmt.Sprint(r.NonTradable))
	}
	if r.Tradable != nil {
		vals.Set("Tradable", fmt.Sprint(r.Tradable))
	}
}
