// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: api.go

package pricedb

import (
	"context"
	"io"
	"net/http"
	"net/url"
	"strconv"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
)

type apiClient struct {
	r *aoni.Client
}

func newAPI(doer any, opts ...aoni.ClientOption) *apiClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	targetReq := aoni.NewClient(doer, append([]aoni.ClientOption{option.WithBaseURL("https://pricedb.io/api/")}, baseOpts...)...)

	return &apiClient{
		r: targetReq,
	}
}

// NewAPI creates a new API client instance with preconfigured execution pipelines.
func NewAPI(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// New creates a new API client instance (alias for NewAPI).
func New(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// R returns the underlying *aoni.Client used by the client.
func (c *apiClient) R() *aoni.Client {
	return c.r
}

func (c *apiClient) GetItem(ctx context.Context, sku string, mods ...aoni.RequestModifier) (*Price, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[Price](ctx, "item/{sku}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) PostItemsBulk(ctx context.Context, req bulkRequest, mods ...aoni.RequestModifier) ([]*Price, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[[]*Price](ctx, "items-bulk", req, allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) Search(ctx context.Context, q string, limit int, mods ...aoni.RequestModifier) (*SearchResult, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "q="...)
	qBytes = append(qBytes, url.QueryEscape(q)...)
	qBytes = append(qBytes, "&limit="...)
	qBytes = strconv.AppendInt(qBytes, int64(limit), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[SearchResult](ctx, "search", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetHistory(ctx context.Context, sku string, start int64, end int64, mods ...aoni.RequestModifier) ([]*Price, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "start="...)
	qBytes = strconv.AppendInt(qBytes, int64(start), 10)
	qBytes = append(qBytes, "&end="...)
	qBytes = strconv.AppendInt(qBytes, int64(end), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[[]*Price](ctx, "item-history/{sku}", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetStats(ctx context.Context, sku string, mods ...aoni.RequestModifier) (*ItemStats, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[ItemStats](ctx, "item-stats/{sku}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) Compare(ctx context.Context, sku1 string, sku2 string, mods ...aoni.RequestModifier) (*CompareResult, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("sku1", sku1))
	allMods = append(allMods, mod.WithVar("sku2", sku2))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[CompareResult](ctx, "compare/{sku1}/{sku2}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) TriggerPriceCheck(ctx context.Context, sku string, mods ...aoni.RequestModifier) error {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	_, err := c.r.PostTo[aoni.NoResponse](ctx, "autob/items/{sku}", nil, allMods...)
	return err
}

func (c *apiClient) HealthCheck(ctx context.Context, mods ...aoni.RequestModifier) (*CacheStats, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[CacheStats](ctx, "cache-stats", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetHealth(ctx context.Context, mods ...aoni.RequestModifier) (string, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[string](ctx, "", allMods...)
	if err != nil {
		return "", err
	}
	return *resp, nil
}

func (c *apiClient) GetItems(ctx context.Context, mods ...aoni.RequestModifier) ([]*ItemBrief, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[[]*ItemBrief](ctx, "items", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetLatestPrices(ctx context.Context, mods ...aoni.RequestModifier) ([]*Price, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[[]*Price](ctx, "latest-prices", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetPrices(ctx context.Context, limit int, offset int, mods ...aoni.RequestModifier) (*PriceHistoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "limit="...)
	qBytes = strconv.AppendInt(qBytes, int64(limit), 10)
	qBytes = append(qBytes, "&offset="...)
	qBytes = strconv.AppendInt(qBytes, int64(offset), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[PriceHistoryResponse](ctx, "prices", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetSnapshot(ctx context.Context, timestamp int64, mods ...aoni.RequestModifier) ([]*Price, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("timestamp", timestamp))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[[]*Price](ctx, "snapshot/{timestamp}", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) GetGraph(ctx context.Context, sku string, header bool, height int, width string, mods ...aoni.RequestModifier) (string, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [128]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "header="...)
	qBytes = strconv.AppendBool(qBytes, header)
	qBytes = append(qBytes, "&height="...)
	qBytes = strconv.AppendInt(qBytes, int64(height), 10)
	qBytes = append(qBytes, "&width="...)
	qBytes = append(qBytes, url.QueryEscape(width)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[string](ctx, "graph/{sku}", allMods...)
	if err != nil {
		return "", err
	}
	return *resp, nil
}

func (c *apiClient) GetAutobItems(ctx context.Context, mods ...aoni.RequestModifier) (*AutobItemsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[AutobItemsResponse](ctx, "autob/items", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetAutobItem(ctx context.Context, sku string, mods ...aoni.RequestModifier) (*Price, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[Price](ctx, "autob/items/{sku}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

type skuClientClient struct {
	r *aoni.Client
}

func newSKUClient(doer any, opts ...aoni.ClientOption) *skuClientClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	targetReq := aoni.NewClient(doer, append([]aoni.ClientOption{option.WithBaseURL("https://sku.pricedb.io/api/")}, baseOpts...)...)

	return &skuClientClient{
		r: targetReq,
	}
}

// NewSKUClient creates a new SKUClient client instance with preconfigured execution pipelines.
func NewSKUClient(doer any, opts ...aoni.ClientOption) SKUClient {
	return newSKUClient(doer, opts...)
}

// R returns the underlying *aoni.Client used by the client.
func (c *skuClientClient) R() *aoni.Client {
	return c.r
}

func (c *skuClientClient) ResolveName(ctx context.Context, name string, mods ...aoni.RequestModifier) (*ResolvedItem, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("name", name))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[ResolvedItem](ctx, "name/{name}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ResolveSKU(ctx context.Context, sku string, mods ...aoni.RequestModifier) (*ResolvedItem, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[ResolvedItem](ctx, "sku/{sku}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetSchema(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[map[string]any](ctx, "schema", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *skuClientClient) GetImageBySKU(ctx context.Context, sku string, mods ...aoni.RequestModifier) ([]byte, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("sku", sku))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.Request(ctx, http.MethodGet, "sku/{sku}/image", allMods...)
	if err != nil {
		return nil, err
	}
	defer aoni.CloseResponse(resp)
	return io.ReadAll(resp.Body)
}

func (c *skuClientClient) GetImageByName(ctx context.Context, name string, mods ...aoni.RequestModifier) ([]byte, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("name", name))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.Request(ctx, http.MethodGet, "name/{name}/image", allMods...)
	if err != nil {
		return nil, err
	}
	defer aoni.CloseResponse(resp)
	return io.ReadAll(resp.Body)
}

func (c *skuClientClient) ListEffects(ctx context.Context, mods ...aoni.RequestModifier) (*EffectsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[EffectsResponse](ctx, "effect/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetEffectByID(ctx context.Context, id int, mods ...aoni.RequestModifier) (*EffectResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", id))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[EffectResponse](ctx, "effect/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetEffectByName(ctx context.Context, name string, mods ...aoni.RequestModifier) (*EffectResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("name", name))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[EffectResponse](ctx, "effect/name/{name}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListPaints(ctx context.Context, mods ...aoni.RequestModifier) (*PaintsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[PaintsResponse](ctx, "paint/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetPaintByID(ctx context.Context, id int, mods ...aoni.RequestModifier) (*PaintResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", id))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[PaintResponse](ctx, "paint/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetPaintByName(ctx context.Context, name string, mods ...aoni.RequestModifier) (*PaintResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("name", name))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[PaintResponse](ctx, "paint/name/{name}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListWears(ctx context.Context, mods ...aoni.RequestModifier) (*WearsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[WearsResponse](ctx, "wear/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetWearByID(ctx context.Context, id int, mods ...aoni.RequestModifier) (*WearResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", id))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[WearResponse](ctx, "wear/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListPaintKits(ctx context.Context, mods ...aoni.RequestModifier) (*PaintKitsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[PaintKitsResponse](ctx, "paintkit/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetPaintKitByID(ctx context.Context, id int, mods ...aoni.RequestModifier) (*PaintKitResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", id))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[PaintKitResponse](ctx, "paintkit/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) GetPaintKitByName(ctx context.Context, name string, mods ...aoni.RequestModifier) (*PaintKitResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("name", name))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[PaintKitResponse](ctx, "paintkit/name/{name}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListStrangeParts(ctx context.Context, mods ...aoni.RequestModifier) (*StrangePartsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[StrangePartsResponse](ctx, "strangepart/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListCrateSeries(ctx context.Context, mods ...aoni.RequestModifier) (*CrateSeriesResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[CrateSeriesResponse](ctx, "crateseries/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListCraftWeapons(ctx context.Context, mods ...aoni.RequestModifier) (*WeaponsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[WeaponsResponse](ctx, "craftweapon/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListUncraftWeapons(ctx context.Context, mods ...aoni.RequestModifier) (*WeaponsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[WeaponsResponse](ctx, "uncraftweapon/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) ListQualities(ctx context.Context, mods ...aoni.RequestModifier) (*QualitiesResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[QualitiesResponse](ctx, "quality/list", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *skuClientClient) DownloadSchema(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[map[string]any](ctx, "download", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

type spellClientClient struct {
	r *aoni.Client
}

func newSpellClient(doer any, opts ...aoni.ClientOption) *spellClientClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	targetReq := aoni.NewClient(doer, append([]aoni.ClientOption{option.WithBaseURL("https://spell.pricedb.io/api/")}, baseOpts...)...)

	return &spellClientClient{
		r: targetReq,
	}
}

// NewSpellClient creates a new SpellClient client instance with preconfigured execution pipelines.
func NewSpellClient(doer any, opts ...aoni.ClientOption) SpellClient {
	return newSpellClient(doer, opts...)
}

// R returns the underlying *aoni.Client used by the client.
func (c *spellClientClient) R() *aoni.Client {
	return c.r
}

func (c *spellClientClient) PredictSpellPrice(ctx context.Context, spells string, item string, mods ...aoni.RequestModifier) (*SpellPredictionResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "spells="...)
	qBytes = append(qBytes, url.QueryEscape(spells)...)
	qBytes = append(qBytes, "&item="...)
	qBytes = append(qBytes, url.QueryEscape(item)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[SpellPredictionResponse](ctx, "spell/predict", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) PredictSpellItem(ctx context.Context, req PredictSpellItemRequest, mods ...aoni.RequestModifier) (*PredictSpellItemResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.PostTo[PredictSpellItemResponse](ctx, "spell/predict-spell-item", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) GetSpellValue(ctx context.Context, ids string, mods ...aoni.RequestModifier) (*SpellValueResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "ids="...)
	qBytes = append(qBytes, url.QueryEscape(ids)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[SpellValueResponse](ctx, "spell/spell-value", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) GetSpellAnalytics(ctx context.Context, mods ...aoni.RequestModifier) ([]*SpellAnalyticsEntry, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[[]*SpellAnalyticsEntry](ctx, "spell/spell-analytics", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *spellClientClient) GetItemSpellPremium(ctx context.Context, item string, ids string, mods ...aoni.RequestModifier) (*ItemSpellPremiumResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "item="...)
	qBytes = append(qBytes, url.QueryEscape(item)...)
	qBytes = append(qBytes, "&ids="...)
	qBytes = append(qBytes, url.QueryEscape(ids)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[ItemSpellPremiumResponse](ctx, "spell/item-spell-premium", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) GetSpellByID(ctx context.Context, id int, mods ...aoni.RequestModifier) (*SpellMetadata, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "id="...)
	qBytes = strconv.AppendInt(qBytes, int64(id), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[SpellMetadata](ctx, "spell/spell-id-to-name", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) GetSpellByName(ctx context.Context, name string, mods ...aoni.RequestModifier) (*SpellMetadata, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "name="...)
	qBytes = append(qBytes, url.QueryEscape(name)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[SpellMetadata](ctx, "spell/spell-name-to-id", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) ListSpells(ctx context.Context, mods ...aoni.RequestModifier) ([]*SpellMetadata, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[[]*SpellMetadata](ctx, "spell/spells", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *spellClientClient) GetSpellFetcherStatus(ctx context.Context, mods ...aoni.RequestModifier) (*FetcherStatusResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[FetcherStatusResponse](ctx, "spell/fetcher-status", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) GetSpellHealth(ctx context.Context, mods ...aoni.RequestModifier) (*SpellHealthResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[SpellHealthResponse](ctx, "spell/health", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) GetServiceStats(ctx context.Context, mods ...aoni.RequestModifier) (*ServiceStatsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[ServiceStatsResponse](ctx, "stats", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *spellClientClient) GetUnifiedStatus(ctx context.Context, mods ...aoni.RequestModifier) (*UnifiedStatusResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.GetTo[UnifiedStatusResponse](ctx, "spell/status-proxy", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
