// Code generated by aoni-gen. DO NOT EDIT.

package mannco

import (
	"context"
	"errors"
	"net/url"
	"strconv"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

type apiClient struct {
	r request.Requester
}

func newAPI(doer any, opts ...aoni.ClientOption) *apiClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	var targetReq request.Requester
	if d, ok := doer.(aoni.RequestDoer); ok {
		targetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL("https://api.mannco.store/")}, baseOpts...)...))
	} else if req, ok := doer.(request.Requester); ok {
		targetReq = request.AsRequester(aoni.Configure(req, append([]aoni.ClientOption{option.WithBaseURL("https://api.mannco.store/")}, baseOpts...)...))
	} else if rd, ok := doer.(interface{ Rest() request.Requester }); ok && rd.Rest() != nil {
		targetReq = rd.Rest()
	} else if rd, ok := doer.(interface{ Requester() request.Requester }); ok && rd.Requester() != nil {
		targetReq = rd.Requester()
	} else {
		targetReq = request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL("https://api.mannco.store/")}, baseOpts...)...))
	}

	return &apiClient{
		r: targetReq,
	}
}

// NewAPI creates a new API client instance with preconfigured execution pipelines.
func NewAPI(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// New creates a new API client instance (alias for NewAPI).
func New(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// R returns the underlying request.Requester used by the client.
func (c *apiClient) R() request.Requester {
	return c.r
}

func (c *apiClient) PostLogin(ctx context.Context, req LoginRequest, mods ...aoni.RequestModifier) (*LoginContent, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool          `json:"success"`
		Content  *LoginContent `json:"content"`
		ErrorMsg string        `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "user/login", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) Disconnect(ctx context.Context, mods ...aoni.RequestModifier) (*DisconnectResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                `json:"success"`
		Content  *DisconnectResponse `json:"content"`
		ErrorMsg string              `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/disconnect", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetUserInfo(ctx context.Context, mods ...aoni.RequestModifier) (*UserInfoResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool              `json:"success"`
		Content  *UserInfoResponse `json:"content"`
		ErrorMsg string            `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/infos", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetBalance(ctx context.Context, mods ...aoni.RequestModifier) (*UserBalanceResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                 `json:"success"`
		Content  *UserBalanceResponse `json:"content"`
		ErrorMsg string               `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/balance", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetNotifications(ctx context.Context, mods ...aoni.RequestModifier) (*NotificationsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                   `json:"success"`
		Content  *NotificationsResponse `json:"content"`
		ErrorMsg string                 `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/notifications", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetIPSessionList(ctx context.Context, query IPSessionListQuery, mods ...aoni.RequestModifier) (*IPSessionListResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                   `json:"success"`
		Content  *IPSessionListResponse `json:"content"`
		ErrorMsg string                 `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/ipList", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetPublicStoreProfile(ctx context.Context, identifier string, mods ...aoni.RequestModifier) (*PublicStoreProfile, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("identifier", identifier))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                `json:"success"`
		Content  *PublicStoreProfile `json:"content"`
		ErrorMsg string              `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/store/{identifier}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetSalesInfos(ctx context.Context, mods ...aoni.RequestModifier) (*SalesInfosResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                `json:"success"`
		Content  *SalesInfosResponse `json:"content"`
		ErrorMsg string              `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getSalesInfos", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetSalesChartInfos(ctx context.Context, query SalesChartQuery, mods ...aoni.RequestModifier) (*SalesChartResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                `json:"success"`
		Content  *SalesChartResponse `json:"content"`
		ErrorMsg string              `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getSalesChartInfos", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetBalanceHistory(ctx context.Context, query BalanceHistoryQuery, mods ...aoni.RequestModifier) (*BalanceHistoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                    `json:"success"`
		Content  *BalanceHistoryResponse `json:"content"`
		ErrorMsg string                  `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getBalanceHistory", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetPurchaseHistory(ctx context.Context, query PurchaseHistoryQuery, mods ...aoni.RequestModifier) (*PurchaseHistoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                     `json:"success"`
		Content  *PurchaseHistoryResponse `json:"content"`
		ErrorMsg string                   `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getPurchaseHistory", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetSalesHistory(ctx context.Context, query SalesHistoryQuery, mods ...aoni.RequestModifier) (*SalesHistoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *SalesHistoryResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getSalesHistory", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetSalesHistoryForUser(ctx context.Context, userid string, query SalesHistoryQuery, mods ...aoni.RequestModifier) (*SalesHistoryResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	allMods = append(allMods, mod.WithVar("userid", userid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *SalesHistoryResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getSalesHistory/{userid}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetCashoutHistory(ctx context.Context, query CashoutHistoryQuery, mods ...aoni.RequestModifier) (*CashoutHistoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                    `json:"success"`
		Content  *CashoutHistoryResponse `json:"content"`
		ErrorMsg string                  `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getCashoutHistory", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetTransactionHistory(ctx context.Context, query TransactionHistoryQuery, mods ...aoni.RequestModifier) (*TransactionHistoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                        `json:"success"`
		Content  *TransactionHistoryResponse `json:"content"`
		ErrorMsg string                      `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getTransactionHistory", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetTransactionDetails(ctx context.Context, transactionID string, mods ...aoni.RequestModifier) (*TransactionDetailsResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "transactionId="...)
	qBytes = append(qBytes, url.QueryEscape(transactionID)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                        `json:"success"`
		Content  *TransactionDetailsResponse `json:"content"`
		ErrorMsg string                      `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getTransactionDetails", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetCryptoDepositHistory(ctx context.Context, query CryptoDepositHistoryQuery, mods ...aoni.RequestModifier) (*CryptoDepositHistoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                          `json:"success"`
		Content  *CryptoDepositHistoryResponse `json:"content"`
		ErrorMsg string                        `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getCryptoDepositHistory", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetItemDetails(ctx context.Context, item string, mods ...aoni.RequestModifier) (*ItemDetails, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("item", item))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool         `json:"success"`
		Content  *ItemDetails `json:"content"`
		ErrorMsg string       `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/details/{item}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetItemSalesGraph(ctx context.Context, item string, period string, mods ...aoni.RequestModifier) (*ItemSalesGraph, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "period="...)
	qBytes = append(qBytes, url.QueryEscape(period)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	allMods = append(allMods, mod.WithVar("item", item))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool            `json:"success"`
		Content  *ItemSalesGraph `json:"content"`
		ErrorMsg string          `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/salesGraph/{item}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetListingCountDirect(ctx context.Context, item string, mods ...aoni.RequestModifier) (*ListingCount, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("item", item))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool          `json:"success"`
		Content  *ListingCount `json:"content"`
		ErrorMsg string        `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/listing/count/{item}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetListingCountForUser(ctx context.Context, item string, userid string, mods ...aoni.RequestModifier) (*ListingCount, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("item", item))
	allMods = append(allMods, mod.WithVar("userid", userid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool          `json:"success"`
		Content  *ListingCount `json:"content"`
		ErrorMsg string        `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/listing/count/{item}/{userid}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetItemListingsDirect(ctx context.Context, item string, query ListingsReq, mods ...aoni.RequestModifier) ([]Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	allMods = append(allMods, mod.WithVar("item", item))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool      `json:"success"`
		Content  []Listing `json:"content"`
		ErrorMsg string    `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/listing/{item}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetItemListingsForUser(ctx context.Context, item string, userid string, query ListingsReq, mods ...aoni.RequestModifier) ([]Listing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	allMods = append(allMods, mod.WithVar("item", item))
	allMods = append(allMods, mod.WithVar("userid", userid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool      `json:"success"`
		Content  []Listing `json:"content"`
		ErrorMsg string    `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/listing/{item}/{userid}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetBuyOrderList(ctx context.Context, item string, mods ...aoni.RequestModifier) (*BuyOrderList, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("item", item))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool          `json:"success"`
		Content  *BuyOrderList `json:"content"`
		ErrorMsg string        `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/buyorderList/{item}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetItemPricing(ctx context.Context, item string, mods ...aoni.RequestModifier) (*ItemPricing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("item", item))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool         `json:"success"`
		Content  *ItemPricing `json:"content"`
		ErrorMsg string       `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/pricing/{item}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetBulkPricingDirect(ctx context.Context, items string, mods ...aoni.RequestModifier) (*BulkPricing, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "items="...)
	qBytes = append(qBytes, url.QueryEscape(items)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool         `json:"success"`
		Content  *BulkPricing `json:"content"`
		ErrorMsg string       `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/pricing/bulk", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetBackpackDetailsTF2(ctx context.Context, backpackid string, mods ...aoni.RequestModifier) (*BackpackDetailsResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("backpackid", backpackid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                     `json:"success"`
		Content  *BackpackDetailsResponse `json:"content"`
		ErrorMsg string                   `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/details/fromid/{backpackid}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetBackpackDetailsCS2(ctx context.Context, backpackid string, mods ...aoni.RequestModifier) (*BackpackDetailsResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("backpackid", backpackid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                     `json:"success"`
		Content  *BackpackDetailsResponse `json:"content"`
		ErrorMsg string                   `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "item/cs/details/fromid/{backpackid}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetItemsOnSale(ctx context.Context, mods ...aoni.RequestModifier) (*GetInventoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *GetInventoryResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "inventory/onSale", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetItemsInInventory(ctx context.Context, mods ...aoni.RequestModifier) (*GetInventoryResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *GetInventoryResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "inventory/onInventory", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) SetPriceDirect(ctx context.Context, req SetPriceReq, mods ...aoni.RequestModifier) (*InventoryMessageResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                      `json:"success"`
		Content  *InventoryMessageResponse `json:"content"`
		ErrorMsg string                    `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "inventory/price", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) WithdrawDirect(ctx context.Context, req WithdrawReq, mods ...aoni.RequestModifier) (*WithdrawResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool              `json:"success"`
		Content  *WithdrawResponse `json:"content"`
		ErrorMsg string            `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "inventory/withdraw", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) CreateBuyOrderDirect(ctx context.Context, req CreateBuyOrderReq, mods ...aoni.RequestModifier) (*DetailsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool             `json:"success"`
		Content  *DetailsResponse `json:"content"`
		ErrorMsg string           `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "item/buyorder", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) UpdateBuyOrderDirect(ctx context.Context, req UpdateBuyOrderReq, mods ...aoni.RequestModifier) (string, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool   `json:"success"`
		Content  string `json:"content"`
		ErrorMsg string `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "item/buyorder/update", req, allMods...)
	if err != nil {
		return "", err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return "", errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) RemoveBuyOrderDirect(ctx context.Context, req RemoveBuyOrderReq, mods ...aoni.RequestModifier) (*DetailsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool             `json:"success"`
		Content  *DetailsResponse `json:"content"`
		ErrorMsg string           `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "item/buyorder/remove", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetUserBuyOrdersForItem(ctx context.Context, item string, mods ...aoni.RequestModifier) (*UserBuyOrderResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("item", item))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *UserBuyOrderResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/buyorder/{item}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetUserBuyOrders(ctx context.Context, query GetUserBuyOrdersQuery, mods ...aoni.RequestModifier) (*UserAllBuyOrdersResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithQuery(query))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                      `json:"success"`
		Content  *UserAllBuyOrdersResponse `json:"content"`
		ErrorMsg string                    `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "user/getBuyorder", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetCart(ctx context.Context, mods ...aoni.RequestModifier) (*GetCartResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool             `json:"success"`
		Content  *GetCartResponse `json:"content"`
		ErrorMsg string           `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "cart/get", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) AddToCartDirect(ctx context.Context, req AddCartReq, mods ...aoni.RequestModifier) (*GetCartResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool             `json:"success"`
		Content  *GetCartResponse `json:"content"`
		ErrorMsg string           `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "cart/add", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) BulkAddToCartDirect(ctx context.Context, req BulkAddCartReq, mods ...aoni.RequestModifier) (*GetCartResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool             `json:"success"`
		Content  *GetCartResponse `json:"content"`
		ErrorMsg string           `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "cart/bulk", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) RemoveFromCartDirect(ctx context.Context, req RemoveCartReq, mods ...aoni.RequestModifier) (*GetCartResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool             `json:"success"`
		Content  *GetCartResponse `json:"content"`
		ErrorMsg string           `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "cart/remove", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) UpdateCart(ctx context.Context, mods ...aoni.RequestModifier) (*UpdateCartResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                `json:"success"`
		Content  *UpdateCartResponse `json:"content"`
		ErrorMsg string              `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "cart/update", nil, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetDepositInfo(ctx context.Context, game int, mods ...aoni.RequestModifier) (*GetDepositInfoResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("game", game))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                    `json:"success"`
		Content  *GetDepositInfoResponse `json:"content"`
		ErrorMsg string                  `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "deposit/{game}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetInstantSellInfo(ctx context.Context, game int, mods ...aoni.RequestModifier) (*GetDepositInfoResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("game", game))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                    `json:"success"`
		Content  *GetDepositInfoResponse `json:"content"`
		ErrorMsg string                  `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "deposit/instantSell/{game}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) CreateDepositTrade(ctx context.Context, req CreateDepositTradeReq, mods ...aoni.RequestModifier) (*CreateDepositTradeResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                        `json:"success"`
		Content  *CreateDepositTradeResponse `json:"content"`
		ErrorMsg string                      `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "deposit/trade", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) CreateInstantSellTrade(ctx context.Context, req CreateInstantSellTradeReq, mods ...aoni.RequestModifier) (*CreateDepositTradeResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                        `json:"success"`
		Content  *CreateDepositTradeResponse `json:"content"`
		ErrorMsg string                      `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "deposit/trade/instant", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetDepositTradeStatus(ctx context.Context, tradeid int, mods ...aoni.RequestModifier) (*TradeStatusResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("tradeid", tradeid))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                 `json:"success"`
		Content  *TradeStatusResponse `json:"content"`
		ErrorMsg string               `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "deposit/tradeStatus/{tradeid}", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetActiveTrades(ctx context.Context, mods ...aoni.RequestModifier) (*GetTradesResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool               `json:"success"`
		Content  *GetTradesResponse `json:"content"`
		ErrorMsg string             `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "trades/active", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetAllTrades(ctx context.Context, mods ...aoni.RequestModifier) (*GetTradesResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool               `json:"success"`
		Content  *GetTradesResponse `json:"content"`
		ErrorMsg string             `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "trades/all", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) ResendTrade(ctx context.Context, id int, mods ...aoni.RequestModifier) (*ResendTradeResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "id="...)
	qBytes = strconv.AppendInt(qBytes, int64(id), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                 `json:"success"`
		Content  *ResendTradeResponse `json:"content"`
		ErrorMsg string               `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "trade/resend", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetReceivedOffers(ctx context.Context, mods ...aoni.RequestModifier) (*GetReceivedOffersResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                       `json:"success"`
		Content  *GetReceivedOffersResponse `json:"content"`
		ErrorMsg string                     `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "offers/received", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) GetMyOffers(ctx context.Context, mods ...aoni.RequestModifier) ([]Offer, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool    `json:"success"`
		Content  []Offer `json:"content"`
		ErrorMsg string  `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "offers/my", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) CreateOfferDirect(ctx context.Context, req CreateOfferReq, mods ...aoni.RequestModifier) (*OfferMessageResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *OfferMessageResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "offers/create", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) AcceptOfferDirect(ctx context.Context, req OfferActionReq, mods ...aoni.RequestModifier) (*OfferMessageResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *OfferMessageResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "offers/accept", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) DeclineOfferDirect(ctx context.Context, req OfferActionReq, mods ...aoni.RequestModifier) (*OfferMessageResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *OfferMessageResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "offers/decline", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) RemoveOfferDirect(ctx context.Context, req OfferActionReq, mods ...aoni.RequestModifier) (*OfferMessageResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool                  `json:"success"`
		Content  *OfferMessageResponse `json:"content"`
		ErrorMsg string                `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "offers/remove", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}

func (c *apiClient) InitiatePayment(ctx context.Context, provider string, req PaymentReq, mods ...aoni.RequestModifier) (*PaymentResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("provider", provider))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	type envelope struct {
		Success  bool             `json:"success"`
		Content  *PaymentResponse `json:"content"`
		ErrorMsg string           `json:"error,omitempty"`
	}

	resp, err := request.PostTo[envelope](ctx, c.r, "payment/{provider}", req, allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Content, nil
}
