// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: api.go

package express

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/lemon4ksan/g-man/pkg/steam/id"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

type apiClient struct {
	r request.Requester
}

func newAPI(doer any, opts ...aoni.ClientOption) *apiClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	var targetReq request.Requester
	if d, ok := doer.(aoni.RequestDoer); ok {
		targetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL("https://api.express-load.com/")}, baseOpts...)...))
	} else if req, ok := doer.(request.Requester); ok {
		targetReq = request.AsRequester(aoni.Configure(req, append([]aoni.ClientOption{option.WithBaseURL("https://api.express-load.com/")}, baseOpts...)...))
	} else if rd, ok := doer.(interface{ Rest() request.Requester }); ok && rd.Rest() != nil {
		targetReq = rd.Rest()
	} else if rd, ok := doer.(interface{ Requester() request.Requester }); ok && rd.Requester() != nil {
		targetReq = rd.Requester()
	} else {
		targetReq = request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL("https://api.express-load.com/")}, baseOpts...)...))
	}

	return &apiClient{
		r: targetReq,
	}
}

// NewAPI creates a new API client instance with preconfigured execution pipelines.
func NewAPI(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// New creates a new API client instance (alias for NewAPI).
func New(doer any, opts ...aoni.ClientOption) API {
	return newAPI(doer, opts...)
}

// R returns the underlying request.Requester used by the client.
func (c *apiClient) R() request.Requester {
	return c.r
}

func (c *apiClient) LiveHealthLiveGet(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "health/live", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) ReadyHealthReadyGet(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[map[string]any](ctx, c.r, "health/ready", allMods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

func (c *apiClient) PublicStatusV1StatusGet(ctx context.Context, mods ...aoni.RequestModifier) (*PublicStatus, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[PublicStatus](ctx, c.r, "v1/status", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) AccountV2V2AccountGet(ctx context.Context, mods ...aoni.RequestModifier) (*V2accountResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[V2accountResponse](ctx, c.r, "v2/account", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) MarketPriceV2V2SteamMarketPriceGet(ctx context.Context, marketHashName string, appID int, currency int, mods ...aoni.RequestModifier) (*V2marketPriceResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [128]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "market_hash_name="...)
	qBytes = append(qBytes, url.QueryEscape(marketHashName)...)
	qBytes = append(qBytes, "&app_id="...)
	qBytes = strconv.AppendInt(qBytes, int64(appID), 10)
	qBytes = append(qBytes, "&currency="...)
	qBytes = strconv.AppendInt(qBytes, int64(currency), 10)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[V2marketPriceResponse](ctx, c.r, "v2/steam/market/price", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) InventoryV2V2SteamUsersSteamIDInventoryAppIDContextIDGet(ctx context.Context, steamID id.ID, appID int, contextID int, cursor string, language string, mods ...aoni.RequestModifier) (*V2inventoryResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "cursor="...)
	qBytes = append(qBytes, url.QueryEscape(cursor)...)
	qBytes = append(qBytes, "&language="...)
	qBytes = append(qBytes, url.QueryEscape(language)...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	allMods = append(allMods, mod.WithVar("steam_id", steamID))
	allMods = append(allMods, mod.WithVar("app_id", appID))
	allMods = append(allMods, mod.WithVar("context_id", contextID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[V2inventoryResponse](ctx, c.r, "v2/steam/users/{steam_id}/inventory/{app_id}/{context_id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// AppendFormData serializes AccountData into url-encoded form bytes on dst buffer (0 B/op).
func (r *AccountData) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.APIKey != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "api_key="...)
		dst = append(dst, fmt.Sprint(r.APIKey)...)
	}
	if r.BalanceCredits != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "balance_credits="...)
		dst = strconv.AppendInt(dst, int64(r.BalanceCredits), 10)
	}
	if r.CustomerID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "customer_id="...)
		dst = append(dst, url.QueryEscape(r.CustomerID)...)
	}
	if r.Usage != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "usage="...)
		dst = append(dst, fmt.Sprint(r.Usage)...)
	}

	return dst
}

// AppendQuery serializes AccountData into query string bytes on dst buffer (0 B/op).
func (r *AccountData) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes AccountData into url.Values without reflection.
func (r *AccountData) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.APIKey != nil {
		vals.Set("api_key", fmt.Sprint(r.APIKey))
	}
	if r.BalanceCredits != 0 {
		vals.Set("balance_credits", strconv.FormatInt(int64(r.BalanceCredits), 10))
	}
	if r.CustomerID != "" {
		vals.Set("customer_id", r.CustomerID)
	}
	if r.Usage != nil {
		vals.Set("usage", fmt.Sprint(r.Usage))
	}
}

// AppendFormData serializes APIKeySummary into url-encoded form bytes on dst buffer (0 B/op).
func (r *APIKeySummary) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.ID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "id="...)
		dst = append(dst, url.QueryEscape(r.ID)...)
	}
	if r.RateLimitPerMinute != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "rate_limit_per_minute="...)
		dst = strconv.AppendInt(dst, int64(r.RateLimitPerMinute), 10)
	}
	for _, v := range r.Scopes {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "scopes="...)
		dst = append(dst, url.QueryEscape(v)...)
	}

	return dst
}

// AppendQuery serializes APIKeySummary into query string bytes on dst buffer (0 B/op).
func (r *APIKeySummary) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes APIKeySummary into url.Values without reflection.
func (r *APIKeySummary) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.ID != "" {
		vals.Set("id", r.ID)
	}
	if r.RateLimitPerMinute != 0 {
		vals.Set("rate_limit_per_minute", strconv.FormatInt(int64(r.RateLimitPerMinute), 10))
	}
	for _, v := range r.Scopes {
		vals.Add("scopes", v)
	}
}

// AppendFormData serializes AvailabilityHour into url-encoded form bytes on dst buffer (0 B/op).
func (r *AvailabilityHour) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Availability != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "availability="...)
		dst = strconv.AppendFloat(dst, float64(r.Availability), 'f', -1, 64)
	}
	if !r.Timestamp.IsZero() {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "timestamp="...)
		dst = append(dst, url.QueryEscape(r.Timestamp.Format(time.RFC3339))...)
	}

	return dst
}

// AppendQuery serializes AvailabilityHour into query string bytes on dst buffer (0 B/op).
func (r *AvailabilityHour) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes AvailabilityHour into url.Values without reflection.
func (r *AvailabilityHour) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Availability != 0 {
		vals.Set("availability", strconv.FormatFloat(float64(r.Availability), 'f', -1, 64))
	}
	if strVal := fmt.Sprint(r.Timestamp); strVal != "" && strVal != "0" {
		vals.Set("timestamp", strVal)
	}
}

// AppendFormData serializes BilledResponseMeta into url-encoded form bytes on dst buffer (0 B/op).
func (r *BilledResponseMeta) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.CreditsCharged != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "credits_charged="...)
		dst = strconv.AppendInt(dst, int64(r.CreditsCharged), 10)
	}
	if r.CreditsRemaining != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "credits_remaining="...)
		dst = strconv.AppendInt(dst, int64(r.CreditsRemaining), 10)
	}
	if r.PriceVersion != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "price_version="...)
		dst = strconv.AppendInt(dst, int64(r.PriceVersion), 10)
	}
	if r.ProductCode != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "product_code="...)
		dst = append(dst, url.QueryEscape(r.ProductCode)...)
	}
	if r.RateLimit != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "rate_limit="...)
		dst = append(dst, fmt.Sprint(r.RateLimit)...)
	}
	if r.RequestID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "request_id="...)
		dst = append(dst, url.QueryEscape(r.RequestID)...)
	}

	return dst
}

// AppendQuery serializes BilledResponseMeta into query string bytes on dst buffer (0 B/op).
func (r *BilledResponseMeta) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes BilledResponseMeta into url.Values without reflection.
func (r *BilledResponseMeta) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.CreditsCharged != 0 {
		vals.Set("credits_charged", strconv.FormatInt(int64(r.CreditsCharged), 10))
	}
	if r.CreditsRemaining != 0 {
		vals.Set("credits_remaining", strconv.FormatInt(int64(r.CreditsRemaining), 10))
	}
	if r.PriceVersion != 0 {
		vals.Set("price_version", strconv.FormatInt(int64(r.PriceVersion), 10))
	}
	if r.ProductCode != "" {
		vals.Set("product_code", r.ProductCode)
	}
	if r.RateLimit != nil {
		vals.Set("rate_limit", fmt.Sprint(r.RateLimit))
	}
	if r.RequestID != "" {
		vals.Set("request_id", r.RequestID)
	}
}

// AppendFormData serializes ErrorDetail into url-encoded form bytes on dst buffer (0 B/op).
func (r *ErrorDetail) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Code != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "code="...)
		dst = append(dst, url.QueryEscape(r.Code)...)
	}
	if r.Detail != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "detail="...)
		dst = append(dst, fmt.Sprint(r.Detail)...)
	}
	if r.Message != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "message="...)
		dst = append(dst, url.QueryEscape(r.Message)...)
	}
	if r.RequestID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "request_id="...)
		dst = append(dst, url.QueryEscape(r.RequestID)...)
	}

	return dst
}

// AppendQuery serializes ErrorDetail into query string bytes on dst buffer (0 B/op).
func (r *ErrorDetail) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ErrorDetail into url.Values without reflection.
func (r *ErrorDetail) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Code != "" {
		vals.Set("code", r.Code)
	}
	if r.Detail != nil {
		vals.Set("detail", fmt.Sprint(r.Detail))
	}
	if r.Message != "" {
		vals.Set("message", r.Message)
	}
	if r.RequestID != "" {
		vals.Set("request_id", r.RequestID)
	}
}

// AppendFormData serializes ErrorResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *ErrorResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Error != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "error="...)
		dst = append(dst, fmt.Sprint(r.Error)...)
	}

	return dst
}

// AppendQuery serializes ErrorResponse into query string bytes on dst buffer (0 B/op).
func (r *ErrorResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ErrorResponse into url.Values without reflection.
func (r *ErrorResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Error != nil {
		vals.Set("error", fmt.Sprint(r.Error))
	}
}

// AppendFormData serializes HttpvalidationError into url-encoded form bytes on dst buffer (0 B/op).
func (r *HttpvalidationError) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	return dst
}

// AppendQuery serializes HttpvalidationError into query string bytes on dst buffer (0 B/op).
func (r *HttpvalidationError) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes HttpvalidationError into url.Values without reflection.
func (r *HttpvalidationError) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
}

// AppendFormData serializes InventoryPage into url-encoded form bytes on dst buffer (0 B/op).
func (r *InventoryPage) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Pagination != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "pagination="...)
		dst = append(dst, fmt.Sprint(r.Pagination)...)
	}
	if r.TotalCount != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "total_count="...)
		dst = strconv.AppendInt(dst, int64(r.TotalCount), 10)
	}

	return dst
}

// AppendQuery serializes InventoryPage into query string bytes on dst buffer (0 B/op).
func (r *InventoryPage) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes InventoryPage into url.Values without reflection.
func (r *InventoryPage) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Pagination != nil {
		vals.Set("pagination", fmt.Sprint(r.Pagination))
	}
	if r.TotalCount != 0 {
		vals.Set("total_count", strconv.FormatInt(int64(r.TotalCount), 10))
	}
}

// AppendFormData serializes InventoryPagination into url-encoded form bytes on dst buffer (0 B/op).
func (r *InventoryPagination) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.HasMore {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "has_more=true"...)
	}
	if r.NextCursor != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "next_cursor="...)
		dst = append(dst, fmt.Sprint(r.NextCursor)...)
	}

	return dst
}

// AppendQuery serializes InventoryPagination into query string bytes on dst buffer (0 B/op).
func (r *InventoryPagination) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes InventoryPagination into url.Values without reflection.
func (r *InventoryPagination) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.HasMore {
		vals.Set("has_more", "true")
	}
	if r.NextCursor != nil {
		vals.Set("next_cursor", fmt.Sprint(r.NextCursor))
	}
}

// AppendFormData serializes InventoryResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *InventoryResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.LastAssetid != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "last_assetid="...)
		dst = append(dst, fmt.Sprint(r.LastAssetid)...)
	}
	if r.MoreItems != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "more_items="...)
		dst = append(dst, fmt.Sprint(r.MoreItems)...)
	}
	if r.Success != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success="...)
		dst = strconv.AppendInt(dst, int64(r.Success), 10)
	}
	if r.TotalInventoryCount != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "total_inventory_count="...)
		dst = strconv.AppendInt(dst, int64(r.TotalInventoryCount), 10)
	}

	return dst
}

// AppendQuery serializes InventoryResponse into query string bytes on dst buffer (0 B/op).
func (r *InventoryResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes InventoryResponse into url.Values without reflection.
func (r *InventoryResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.LastAssetid != nil {
		vals.Set("last_assetid", fmt.Sprint(r.LastAssetid))
	}
	if r.MoreItems != nil {
		vals.Set("more_items", fmt.Sprint(r.MoreItems))
	}
	if r.Success != 0 {
		vals.Set("success", strconv.FormatInt(int64(r.Success), 10))
	}
	if r.TotalInventoryCount != 0 {
		vals.Set("total_inventory_count", strconv.FormatInt(int64(r.TotalInventoryCount), 10))
	}
}

// AppendFormData serializes MarketPriceData into url-encoded form bytes on dst buffer (0 B/op).
func (r *MarketPriceData) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.LowestPrice != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "lowest_price="...)
		dst = append(dst, fmt.Sprint(r.LowestPrice)...)
	}
	if r.MedianPrice != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "median_price="...)
		dst = append(dst, fmt.Sprint(r.MedianPrice)...)
	}
	if r.Volume != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "volume="...)
		dst = append(dst, fmt.Sprint(r.Volume)...)
	}

	return dst
}

// AppendQuery serializes MarketPriceData into query string bytes on dst buffer (0 B/op).
func (r *MarketPriceData) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes MarketPriceData into url.Values without reflection.
func (r *MarketPriceData) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.LowestPrice != nil {
		vals.Set("lowest_price", fmt.Sprint(r.LowestPrice))
	}
	if r.MedianPrice != nil {
		vals.Set("median_price", fmt.Sprint(r.MedianPrice))
	}
	if r.Volume != nil {
		vals.Set("volume", fmt.Sprint(r.Volume))
	}
}

// AppendFormData serializes PublicStatus into url-encoded form bytes on dst buffer (0 B/op).
func (r *PublicStatus) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Status != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "status="...)
		dst = append(dst, url.QueryEscape(r.Status)...)
	}
	if !r.UpdatedAt.IsZero() {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "updated_at="...)
		dst = append(dst, url.QueryEscape(r.UpdatedAt.Format(time.RFC3339))...)
	}

	return dst
}

// AppendQuery serializes PublicStatus into query string bytes on dst buffer (0 B/op).
func (r *PublicStatus) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes PublicStatus into url.Values without reflection.
func (r *PublicStatus) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Status != "" {
		vals.Set("status", r.Status)
	}
	if strVal := fmt.Sprint(r.UpdatedAt); strVal != "" && strVal != "0" {
		vals.Set("updated_at", strVal)
	}
}

// AppendFormData serializes RateLimitMeta into url-encoded form bytes on dst buffer (0 B/op).
func (r *RateLimitMeta) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.LimitPerMinute != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "limit_per_minute="...)
		dst = strconv.AppendInt(dst, int64(r.LimitPerMinute), 10)
	}
	if r.Remaining != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "remaining="...)
		dst = strconv.AppendInt(dst, int64(r.Remaining), 10)
	}
	if r.ResetSeconds != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "reset_seconds="...)
		dst = strconv.AppendInt(dst, int64(r.ResetSeconds), 10)
	}

	return dst
}

// AppendQuery serializes RateLimitMeta into query string bytes on dst buffer (0 B/op).
func (r *RateLimitMeta) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes RateLimitMeta into url.Values without reflection.
func (r *RateLimitMeta) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.LimitPerMinute != 0 {
		vals.Set("limit_per_minute", strconv.FormatInt(int64(r.LimitPerMinute), 10))
	}
	if r.Remaining != 0 {
		vals.Set("remaining", strconv.FormatInt(int64(r.Remaining), 10))
	}
	if r.ResetSeconds != 0 {
		vals.Set("reset_seconds", strconv.FormatInt(int64(r.ResetSeconds), 10))
	}
}

// AppendFormData serializes ResponseMeta into url-encoded form bytes on dst buffer (0 B/op).
func (r *ResponseMeta) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.RequestID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "request_id="...)
		dst = append(dst, url.QueryEscape(r.RequestID)...)
	}

	return dst
}

// AppendQuery serializes ResponseMeta into query string bytes on dst buffer (0 B/op).
func (r *ResponseMeta) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ResponseMeta into url.Values without reflection.
func (r *ResponseMeta) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.RequestID != "" {
		vals.Set("request_id", r.RequestID)
	}
}

// AppendFormData serializes ServiceStatus into url-encoded form bytes on dst buffer (0 B/op).
func (r *ServiceStatus) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Name != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "name="...)
		dst = append(dst, url.QueryEscape(r.Name)...)
	}
	if r.Status != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "status="...)
		dst = append(dst, url.QueryEscape(r.Status)...)
	}

	return dst
}

// AppendQuery serializes ServiceStatus into query string bytes on dst buffer (0 B/op).
func (r *ServiceStatus) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ServiceStatus into url.Values without reflection.
func (r *ServiceStatus) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Name != "" {
		vals.Set("name", r.Name)
	}
	if r.Status != "" {
		vals.Set("status", r.Status)
	}
}

// AppendFormData serializes SteamAsset into url-encoded form bytes on dst buffer (0 B/op).
func (r *SteamAsset) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Amount != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "amount="...)
		dst = append(dst, url.QueryEscape(r.Amount)...)
	}
	if r.Appid != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "appid="...)
		dst = strconv.AppendInt(dst, int64(r.Appid), 10)
	}
	if r.Assetid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "assetid="...)
		dst = append(dst, url.QueryEscape(r.Assetid)...)
	}
	if r.Classid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "classid="...)
		dst = append(dst, url.QueryEscape(r.Classid)...)
	}
	if r.Contextid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "contextid="...)
		dst = append(dst, url.QueryEscape(r.Contextid)...)
	}
	if r.Instanceid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "instanceid="...)
		dst = append(dst, url.QueryEscape(r.Instanceid)...)
	}

	return dst
}

// AppendQuery serializes SteamAsset into query string bytes on dst buffer (0 B/op).
func (r *SteamAsset) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes SteamAsset into url.Values without reflection.
func (r *SteamAsset) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Amount != "" {
		vals.Set("amount", r.Amount)
	}
	if r.Appid != 0 {
		vals.Set("appid", strconv.FormatInt(int64(r.Appid), 10))
	}
	if r.Assetid != "" {
		vals.Set("assetid", r.Assetid)
	}
	if r.Classid != "" {
		vals.Set("classid", r.Classid)
	}
	if r.Contextid != "" {
		vals.Set("contextid", r.Contextid)
	}
	if r.Instanceid != "" {
		vals.Set("instanceid", r.Instanceid)
	}
}

// AppendFormData serializes SteamDescription into url-encoded form bytes on dst buffer (0 B/op).
func (r *SteamDescription) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Appid != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "appid="...)
		dst = strconv.AppendInt(dst, int64(r.Appid), 10)
	}
	if r.Classid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "classid="...)
		dst = append(dst, url.QueryEscape(r.Classid)...)
	}
	if r.Commodity != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "commodity="...)
		dst = append(dst, fmt.Sprint(r.Commodity)...)
	}
	if r.Instanceid != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "instanceid="...)
		dst = append(dst, url.QueryEscape(r.Instanceid)...)
	}
	if r.MarketHashName != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "market_hash_name="...)
		dst = append(dst, fmt.Sprint(r.MarketHashName)...)
	}
	if r.MarketName != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "market_name="...)
		dst = append(dst, fmt.Sprint(r.MarketName)...)
	}
	if r.Marketable != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "marketable="...)
		dst = append(dst, fmt.Sprint(r.Marketable)...)
	}
	if r.Name != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "name="...)
		dst = append(dst, fmt.Sprint(r.Name)...)
	}
	if r.Tradable != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "tradable="...)
		dst = append(dst, fmt.Sprint(r.Tradable)...)
	}
	if r.Type != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "type="...)
		dst = append(dst, fmt.Sprint(r.Type)...)
	}

	return dst
}

// AppendQuery serializes SteamDescription into query string bytes on dst buffer (0 B/op).
func (r *SteamDescription) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes SteamDescription into url.Values without reflection.
func (r *SteamDescription) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Appid != 0 {
		vals.Set("appid", strconv.FormatInt(int64(r.Appid), 10))
	}
	if r.Classid != "" {
		vals.Set("classid", r.Classid)
	}
	if r.Commodity != nil {
		vals.Set("commodity", fmt.Sprint(r.Commodity))
	}
	if r.Instanceid != "" {
		vals.Set("instanceid", r.Instanceid)
	}
	if r.MarketHashName != nil {
		vals.Set("market_hash_name", fmt.Sprint(r.MarketHashName))
	}
	if r.MarketName != nil {
		vals.Set("market_name", fmt.Sprint(r.MarketName))
	}
	if r.Marketable != nil {
		vals.Set("marketable", fmt.Sprint(r.Marketable))
	}
	if r.Name != nil {
		vals.Set("name", fmt.Sprint(r.Name))
	}
	if r.Tradable != nil {
		vals.Set("tradable", fmt.Sprint(r.Tradable))
	}
	if r.Type != nil {
		vals.Set("type", fmt.Sprint(r.Type))
	}
}

// AppendFormData serializes SteamTag into url-encoded form bytes on dst buffer (0 B/op).
func (r *SteamTag) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Category != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "category="...)
		dst = append(dst, url.QueryEscape(r.Category)...)
	}
	if r.InternalName != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "internal_name="...)
		dst = append(dst, url.QueryEscape(r.InternalName)...)
	}
	if r.LocalizedCategoryName != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "localized_category_name="...)
		dst = append(dst, fmt.Sprint(r.LocalizedCategoryName)...)
	}
	if r.LocalizedTagName != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "localized_tag_name="...)
		dst = append(dst, fmt.Sprint(r.LocalizedTagName)...)
	}

	return dst
}

// AppendQuery serializes SteamTag into query string bytes on dst buffer (0 B/op).
func (r *SteamTag) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes SteamTag into url.Values without reflection.
func (r *SteamTag) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Category != "" {
		vals.Set("category", r.Category)
	}
	if r.InternalName != "" {
		vals.Set("internal_name", r.InternalName)
	}
	if r.LocalizedCategoryName != nil {
		vals.Set("localized_category_name", fmt.Sprint(r.LocalizedCategoryName))
	}
	if r.LocalizedTagName != nil {
		vals.Set("localized_tag_name", fmt.Sprint(r.LocalizedTagName))
	}
}

// AppendFormData serializes UsageSummary into url-encoded form bytes on dst buffer (0 B/op).
func (r *UsageSummary) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.CreditsCharged != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "credits_charged="...)
		dst = strconv.AppendInt(dst, int64(r.CreditsCharged), 10)
	}
	if r.Errors != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "errors="...)
		dst = strconv.AppendInt(dst, int64(r.Errors), 10)
	}
	if r.PeriodEnd != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "period_end="...)
		dst = append(dst, url.QueryEscape(r.PeriodEnd)...)
	}
	if r.PeriodStart != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "period_start="...)
		dst = append(dst, url.QueryEscape(r.PeriodStart)...)
	}
	if r.Requests != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "requests="...)
		dst = strconv.AppendInt(dst, int64(r.Requests), 10)
	}

	return dst
}

// AppendQuery serializes UsageSummary into query string bytes on dst buffer (0 B/op).
func (r *UsageSummary) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes UsageSummary into url.Values without reflection.
func (r *UsageSummary) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.CreditsCharged != 0 {
		vals.Set("credits_charged", strconv.FormatInt(int64(r.CreditsCharged), 10))
	}
	if r.Errors != 0 {
		vals.Set("errors", strconv.FormatInt(int64(r.Errors), 10))
	}
	if r.PeriodEnd != "" {
		vals.Set("period_end", r.PeriodEnd)
	}
	if r.PeriodStart != "" {
		vals.Set("period_start", r.PeriodStart)
	}
	if r.Requests != 0 {
		vals.Set("requests", strconv.FormatInt(int64(r.Requests), 10))
	}
}

// AppendFormData serializes V2accountResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *V2accountResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Data != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "data="...)
		dst = append(dst, fmt.Sprint(r.Data)...)
	}
	if r.Meta != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "meta="...)
		dst = append(dst, fmt.Sprint(r.Meta)...)
	}
	if r.Success {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success=true"...)
	}

	return dst
}

// AppendQuery serializes V2accountResponse into query string bytes on dst buffer (0 B/op).
func (r *V2accountResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V2accountResponse into url.Values without reflection.
func (r *V2accountResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Data != nil {
		vals.Set("data", fmt.Sprint(r.Data))
	}
	if r.Meta != nil {
		vals.Set("meta", fmt.Sprint(r.Meta))
	}
	if r.Success {
		vals.Set("success", "true")
	}
}

// AppendFormData serializes V2errorDetail into url-encoded form bytes on dst buffer (0 B/op).
func (r *V2errorDetail) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if strVal := fmt.Sprint(r.Code); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "code="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.Detail != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "detail="...)
		dst = append(dst, fmt.Sprint(r.Detail)...)
	}
	if strVal := fmt.Sprint(r.Message); strVal != "" && strVal != "0" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "message="...)
		dst = append(dst, url.QueryEscape(strVal)...)
	}
	if r.RequestID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "request_id="...)
		dst = append(dst, url.QueryEscape(r.RequestID)...)
	}

	return dst
}

// AppendQuery serializes V2errorDetail into query string bytes on dst buffer (0 B/op).
func (r *V2errorDetail) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V2errorDetail into url.Values without reflection.
func (r *V2errorDetail) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if strVal := fmt.Sprint(r.Code); strVal != "" && strVal != "0" {
		vals.Set("code", strVal)
	}
	if r.Detail != nil {
		vals.Set("detail", fmt.Sprint(r.Detail))
	}
	if strVal := fmt.Sprint(r.Message); strVal != "" && strVal != "0" {
		vals.Set("message", strVal)
	}
	if r.RequestID != "" {
		vals.Set("request_id", r.RequestID)
	}
}

// AppendFormData serializes V2errorResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *V2errorResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Error != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "error="...)
		dst = append(dst, fmt.Sprint(r.Error)...)
	}
	if r.Success {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success=true"...)
	}

	return dst
}

// AppendQuery serializes V2errorResponse into query string bytes on dst buffer (0 B/op).
func (r *V2errorResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V2errorResponse into url.Values without reflection.
func (r *V2errorResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Error != nil {
		vals.Set("error", fmt.Sprint(r.Error))
	}
	if r.Success {
		vals.Set("success", "true")
	}
}

// AppendFormData serializes V2inventoryErrorDetail into url-encoded form bytes on dst buffer (0 B/op).
func (r *V2inventoryErrorDetail) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Code != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "code="...)
		dst = append(dst, fmt.Sprint(r.Code)...)
	}
	if r.Detail != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "detail="...)
		dst = append(dst, fmt.Sprint(r.Detail)...)
	}
	if r.Message != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "message="...)
		dst = append(dst, fmt.Sprint(r.Message)...)
	}
	if r.RequestID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "request_id="...)
		dst = append(dst, url.QueryEscape(r.RequestID)...)
	}

	return dst
}

// AppendQuery serializes V2inventoryErrorDetail into query string bytes on dst buffer (0 B/op).
func (r *V2inventoryErrorDetail) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V2inventoryErrorDetail into url.Values without reflection.
func (r *V2inventoryErrorDetail) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Code != nil {
		vals.Set("code", fmt.Sprint(r.Code))
	}
	if r.Detail != nil {
		vals.Set("detail", fmt.Sprint(r.Detail))
	}
	if r.Message != nil {
		vals.Set("message", fmt.Sprint(r.Message))
	}
	if r.RequestID != "" {
		vals.Set("request_id", r.RequestID)
	}
}

// AppendFormData serializes V2inventoryErrorResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *V2inventoryErrorResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Error != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "error="...)
		dst = append(dst, fmt.Sprint(r.Error)...)
	}
	if r.Success {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success=true"...)
	}

	return dst
}

// AppendQuery serializes V2inventoryErrorResponse into query string bytes on dst buffer (0 B/op).
func (r *V2inventoryErrorResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V2inventoryErrorResponse into url.Values without reflection.
func (r *V2inventoryErrorResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Error != nil {
		vals.Set("error", fmt.Sprint(r.Error))
	}
	if r.Success {
		vals.Set("success", "true")
	}
}

// AppendFormData serializes V2inventoryResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *V2inventoryResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Data != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "data="...)
		dst = append(dst, fmt.Sprint(r.Data)...)
	}
	if r.Meta != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "meta="...)
		dst = append(dst, fmt.Sprint(r.Meta)...)
	}
	if r.Success {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success=true"...)
	}

	return dst
}

// AppendQuery serializes V2inventoryResponse into query string bytes on dst buffer (0 B/op).
func (r *V2inventoryResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V2inventoryResponse into url.Values without reflection.
func (r *V2inventoryResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Data != nil {
		vals.Set("data", fmt.Sprint(r.Data))
	}
	if r.Meta != nil {
		vals.Set("meta", fmt.Sprint(r.Meta))
	}
	if r.Success {
		vals.Set("success", "true")
	}
}

// AppendFormData serializes V2marketPriceResponse into url-encoded form bytes on dst buffer (0 B/op).
func (r *V2marketPriceResponse) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Data != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "data="...)
		dst = append(dst, fmt.Sprint(r.Data)...)
	}
	if r.Meta != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "meta="...)
		dst = append(dst, fmt.Sprint(r.Meta)...)
	}
	if r.Success {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "success=true"...)
	}

	return dst
}

// AppendQuery serializes V2marketPriceResponse into query string bytes on dst buffer (0 B/op).
func (r *V2marketPriceResponse) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes V2marketPriceResponse into url.Values without reflection.
func (r *V2marketPriceResponse) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Data != nil {
		vals.Set("data", fmt.Sprint(r.Data))
	}
	if r.Meta != nil {
		vals.Set("meta", fmt.Sprint(r.Meta))
	}
	if r.Success {
		vals.Set("success", "true")
	}
}

// AppendFormData serializes ValidationError into url-encoded form bytes on dst buffer (0 B/op).
func (r *ValidationError) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Input != nil {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "input="...)
		dst = append(dst, fmt.Sprint(r.Input)...)
	}
	if r.Msg != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "msg="...)
		dst = append(dst, url.QueryEscape(r.Msg)...)
	}
	if r.Type != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "type="...)
		dst = append(dst, url.QueryEscape(r.Type)...)
	}

	return dst
}

// AppendQuery serializes ValidationError into query string bytes on dst buffer (0 B/op).
func (r *ValidationError) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

// EncodeValues serializes ValidationError into url.Values without reflection.
func (r *ValidationError) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Input != nil {
		vals.Set("input", fmt.Sprint(r.Input))
	}
	if r.Msg != "" {
		vals.Set("msg", r.Msg)
	}
	if r.Type != "" {
		vals.Set("type", r.Type)
	}
}
