// Code generated by oapi-gen-aoni. DO NOT EDIT.

package express

import (
	"context"
	"github.com/lemon4ksan/g-man/pkg/steam/id"
	"time"

	"github.com/lemon4ksan/aoni"
)

// BaseURL is the default API base endpoint.
const BaseURL = "https://api.express-load.com/"

// @aoni:dto casing=snake_case omitempty=true
type AccountData struct {
	APIKey         *APIKeySummary `json:"api_key"`
	BalanceCredits int            `json:"balance_credits"`
	CustomerID     string         `json:"customer_id"`
	Usage          *UsageSummary  `json:"usage"`
}

// @aoni:dto casing=snake_case omitempty=true
type APIKeySummary struct {
	ID                 string   `json:"id"`
	RateLimitPerMinute int      `json:"rate_limit_per_minute"`
	Scopes             []string `json:"scopes"`
}

// @aoni:dto casing=snake_case omitempty=true
type AvailabilityHour struct {
	Availability float64   `json:"availability"`
	Timestamp    time.Time `json:"timestamp"`
}

// BilledResponseMeta — Stable billing and rate-limit metadata for a charged API operation.
// @aoni:dto casing=snake_case omitempty=true
type BilledResponseMeta struct {
	CreditsCharged   int    `json:"credits_charged"`
	CreditsRemaining int    `json:"credits_remaining"`
	PriceVersion     int    `json:"price_version"`
	ProductCode      string `json:"product_code"`
	// The API-key request budget after this response.
	RateLimit *RateLimitMeta `json:"rate_limit"`
	RequestID string         `json:"request_id"`
}

// @aoni:dto casing=snake_case omitempty=true
type ErrorDetail struct {
	Code      string `json:"code"`
	Detail    any    `json:"detail,omitempty"`
	Message   string `json:"message"`
	RequestID string `json:"request_id"`
}

// @aoni:dto casing=snake_case omitempty=true
type ErrorResponse struct {
	Error *ErrorDetail `json:"error"`
}

// @aoni:dto casing=snake_case omitempty=true
type HttpvalidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// InventoryErrorCode — Errors specific to Steam inventory requests.
type InventoryErrorCode string

const (
	InventoryErrorCodeInventoryPrivate InventoryErrorCode = "inventory_private"
)

// InventoryErrorMessage — Stable customer-facing messages specific to inventory requests.
type InventoryErrorMessage string

const (
	InventoryErrorMessageInventoryIsPrivate InventoryErrorMessage = "Inventory is private"
)

// @aoni:dto casing=snake_case omitempty=true
type InventoryPage struct {
	Assets       []SteamAsset         `json:"assets"`
	Descriptions []SteamDescription   `json:"descriptions"`
	Pagination   *InventoryPagination `json:"pagination"`
	TotalCount   int                  `json:"total_count"`
}

// @aoni:dto casing=snake_case omitempty=true
type InventoryPagination struct {
	HasMore bool `json:"has_more"`
	// Opaque cursor for the next page. Pass it as `cursor` without modifying it.
	NextCursor any `json:"next_cursor,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type InventoryResponse struct {
	Assets              []SteamAsset       `json:"assets"`
	Descriptions        []SteamDescription `json:"descriptions"`
	LastAssetid         any                `json:"last_assetid,omitempty"`
	MoreItems           any                `json:"more_items,omitempty"`
	Success             int                `json:"success"`
	TotalInventoryCount int                `json:"total_inventory_count"`
}

// @aoni:dto casing=snake_case omitempty=true
type MarketPriceData struct {
	LowestPrice any `json:"lowest_price"`
	MedianPrice any `json:"median_price"`
	Volume      any `json:"volume"`
}

// PublicAPIErrorCode — Errors shared by public API authentication, billing, and upstream execution.
type PublicAPIErrorCode string

const (
	PublicAPIErrorCodeAPIKeyRequired          PublicAPIErrorCode = "api_key_required"
	PublicAPIErrorCodeInvalidAPIKey           PublicAPIErrorCode = "invalid_api_key"
	PublicAPIErrorCodeProductNotAllowed       PublicAPIErrorCode = "product_not_allowed"
	PublicAPIErrorCodeInsufficientCredits     PublicAPIErrorCode = "insufficient_credits"
	PublicAPIErrorCodeProductUnavailable      PublicAPIErrorCode = "product_unavailable"
	PublicAPIErrorCodeIdempotencyConflict     PublicAPIErrorCode = "idempotency_conflict"
	PublicAPIErrorCodeIdempotencyReplay       PublicAPIErrorCode = "idempotency_replay"
	PublicAPIErrorCodeRateLimitExceeded       PublicAPIErrorCode = "rate_limit_exceeded"
	PublicAPIErrorCodeValidationError         PublicAPIErrorCode = "validation_error"
	PublicAPIErrorCodeGatewaySaturated        PublicAPIErrorCode = "gateway_saturated"
	PublicAPIErrorCodeNotFound                PublicAPIErrorCode = "not_found"
	PublicAPIErrorCodeUpstreamUnavailable     PublicAPIErrorCode = "upstream_unavailable"
	PublicAPIErrorCodeUpstreamInvalidResponse PublicAPIErrorCode = "upstream_invalid_response"
	PublicAPIErrorCodeInternalServerError     PublicAPIErrorCode = "internal_server_error"
)

// PublicAPIErrorMessage — Stable customer-facing messages shared by public v2 endpoints.
type PublicAPIErrorMessage string

const (
	PublicAPIErrorMessageXAPIKeyHeaderIsRequired                    PublicAPIErrorMessage = "X-API-Key header is required"
	PublicAPIErrorMessageInvalidAPIKey                              PublicAPIErrorMessage = "Invalid API key"
	PublicAPIErrorMessageThisAPIKeyCannotAccessTheRequestedEndpoint PublicAPIErrorMessage = "This API key cannot access the requested endpoint"
	PublicAPIErrorMessageInsufficientCredits                        PublicAPIErrorMessage = "Insufficient credits"
	PublicAPIErrorMessageThisEndpointIsTemporarilyUnavailable       PublicAPIErrorMessage = "This endpoint is temporarily unavailable"
	PublicAPIErrorMessageIdempotencyKeyWasUsedWithADifferentRequest PublicAPIErrorMessage = "Idempotency key was used with a different request"
	PublicAPIErrorMessageRequestWasAlreadyAccepted                  PublicAPIErrorMessage = "Request was already accepted"
	PublicAPIErrorMessageAPIKeyRateLimitExceeded                    PublicAPIErrorMessage = "API key rate limit exceeded"
	PublicAPIErrorMessageOneOrMoreFieldsAreInvalid                  PublicAPIErrorMessage = "One or more fields are invalid"
	PublicAPIErrorMessageGatewayCapacityIsTemporarilyUnavailable    PublicAPIErrorMessage = "Gateway capacity is temporarily unavailable"
	PublicAPIErrorMessageSteamDataWasNotFound                       PublicAPIErrorMessage = "Steam data was not found"
	PublicAPIErrorMessageSteamIsTemporarilyUnavailable              PublicAPIErrorMessage = "Steam is temporarily unavailable"
	PublicAPIErrorMessageSteamReturnedAnInvalidResponse             PublicAPIErrorMessage = "Steam returned an invalid response"
	PublicAPIErrorMessageAnUnexpectedErrorOccurred                  PublicAPIErrorMessage = "An unexpected error occurred"
)

// @aoni:dto casing=snake_case omitempty=true
type PublicStatus struct {
	History   []AvailabilityHour `json:"history"`
	Services  []ServiceStatus    `json:"services"`
	Status    string             `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// RateLimitMeta — The API-key request budget after this response.
// @aoni:dto casing=snake_case omitempty=true
type RateLimitMeta struct {
	LimitPerMinute int `json:"limit_per_minute"`
	Remaining      int `json:"remaining"`
	ResetSeconds   int `json:"reset_seconds"`
}

// ResponseMeta — Metadata present on every successful v2 response.
// @aoni:dto casing=snake_case omitempty=true
type ResponseMeta struct {
	RequestID string `json:"request_id"`
}

// @aoni:dto casing=snake_case omitempty=true
type ServiceStatus struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

// @aoni:dto casing=snake_case omitempty=true
type SteamAsset struct {
	Amount     string `json:"amount"`
	Appid      int    `json:"appid"`
	Assetid    string `json:"assetid"`
	Classid    string `json:"classid"`
	Contextid  string `json:"contextid"`
	Instanceid string `json:"instanceid"`
}

// SteamCurrency — Supported Steam ECurrency value. Names and numeric values follow Steamworks.
type SteamCurrency int

// @aoni:dto casing=snake_case omitempty=true
type SteamDescription struct {
	Appid          int        `json:"appid"`
	Classid        string     `json:"classid"`
	Commodity      any        `json:"commodity,omitempty"`
	Instanceid     string     `json:"instanceid"`
	MarketHashName any        `json:"market_hash_name,omitempty"`
	MarketName     any        `json:"market_name,omitempty"`
	Marketable     any        `json:"marketable,omitempty"`
	Name           any        `json:"name,omitempty"`
	Tags           []SteamTag `json:"tags,omitempty"`
	Tradable       any        `json:"tradable,omitempty"`
	Type           any        `json:"type,omitempty"`
}

// SteamLanguage — Steam-supported localized inventory description languages.
type SteamLanguage string

const (
	SteamLanguageArabic     SteamLanguage = "arabic"
	SteamLanguageBulgarian  SteamLanguage = "bulgarian"
	SteamLanguageBrazilian  SteamLanguage = "brazilian"
	SteamLanguageCzech      SteamLanguage = "czech"
	SteamLanguageDanish     SteamLanguage = "danish"
	SteamLanguageDutch      SteamLanguage = "dutch"
	SteamLanguageEnglish    SteamLanguage = "english"
	SteamLanguageFinnish    SteamLanguage = "finnish"
	SteamLanguageFrench     SteamLanguage = "french"
	SteamLanguageGerman     SteamLanguage = "german"
	SteamLanguageGreek      SteamLanguage = "greek"
	SteamLanguageHungarian  SteamLanguage = "hungarian"
	SteamLanguageIndonesian SteamLanguage = "indonesian"
	SteamLanguageItalian    SteamLanguage = "italian"
	SteamLanguageJapanese   SteamLanguage = "japanese"
	SteamLanguageKoreana    SteamLanguage = "koreana"
	SteamLanguageLatam      SteamLanguage = "latam"
	SteamLanguageNorwegian  SteamLanguage = "norwegian"
	SteamLanguagePolish     SteamLanguage = "polish"
	SteamLanguagePortuguese SteamLanguage = "portuguese"
	SteamLanguageRomanian   SteamLanguage = "romanian"
	SteamLanguageRussian    SteamLanguage = "russian"
	SteamLanguageSchinese   SteamLanguage = "schinese"
	SteamLanguageSpanish    SteamLanguage = "spanish"
	SteamLanguageSwedish    SteamLanguage = "swedish"
	SteamLanguageTchinese   SteamLanguage = "tchinese"
	SteamLanguageThai       SteamLanguage = "thai"
	SteamLanguageTurkish    SteamLanguage = "turkish"
	SteamLanguageUkrainian  SteamLanguage = "ukrainian"
	SteamLanguageVietnamese SteamLanguage = "vietnamese"
)

// @aoni:dto casing=snake_case omitempty=true
type SteamTag struct {
	Category              string `json:"category"`
	InternalName          string `json:"internal_name"`
	LocalizedCategoryName any    `json:"localized_category_name,omitempty"`
	LocalizedTagName      any    `json:"localized_tag_name,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type UsageSummary struct {
	CreditsCharged int    `json:"credits_charged"`
	Errors         int    `json:"errors"`
	PeriodEnd      string `json:"period_end"`
	PeriodStart    string `json:"period_start"`
	Requests       int    `json:"requests"`
}

// @aoni:dto casing=snake_case omitempty=true
type V2accountResponse struct {
	Data *AccountData `json:"data"`
	// Metadata present on every successful v2 response.
	Meta    *ResponseMeta `json:"meta"`
	Success bool          `json:"success,omitempty"`
}

// V2errorDetail — Error detail for failures shared by all public v2 endpoints.
// @aoni:dto casing=snake_case omitempty=true
type V2errorDetail struct {
	// Errors shared by public API authentication, billing, and upstream execution.
	Code   PublicAPIErrorCode `json:"code"`
	Detail any                `json:"detail,omitempty"`
	// Stable customer-facing messages shared by public v2 endpoints.
	Message   PublicAPIErrorMessage `json:"message"`
	RequestID string                `json:"request_id"`
}

// @aoni:dto casing=snake_case omitempty=true
type V2errorResponse struct {
	// Error detail for failures shared by all public v2 endpoints.
	Error   *V2errorDetail `json:"error"`
	Success bool           `json:"success,omitempty"`
}

// V2inventoryErrorDetail — Shared public errors plus inventory-specific failures.
// @aoni:dto casing=snake_case omitempty=true
type V2inventoryErrorDetail struct {
	Code      any    `json:"code"`
	Detail    any    `json:"detail,omitempty"`
	Message   any    `json:"message"`
	RequestID string `json:"request_id"`
}

// @aoni:dto casing=snake_case omitempty=true
type V2inventoryErrorResponse struct {
	// Shared public errors plus inventory-specific failures.
	Error   *V2inventoryErrorDetail `json:"error"`
	Success bool                    `json:"success,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V2inventoryResponse struct {
	Data *InventoryPage `json:"data"`
	// Stable billing and rate-limit metadata for a charged API operation.
	Meta    *BilledResponseMeta `json:"meta"`
	Success bool                `json:"success,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type V2marketPriceResponse struct {
	Data *MarketPriceData `json:"data"`
	// Stable billing and rate-limit metadata for a charged API operation.
	Meta    *BilledResponseMeta `json:"meta"`
	Success bool                `json:"success,omitempty"`
}

// @aoni:dto casing=snake_case omitempty=true
type ValidationError struct {
	Ctx   map[string]any `json:"ctx,omitempty"`
	Input any            `json:"input,omitempty"`
	Loc   []any          `json:"loc"`
	Msg   string         `json:"msg"`
	Type  string         `json:"type"`
}

// @aoni:service casing=snake_case
// @base_url "https://api.express-load.com/"
// @version "v2.0.0"
// @source "express.json"
type API interface {
	// LiveHealthLiveGet — Check process liveness
	//
	// @get "health/live"
	// @bind "live_health_live_get"
	GetLiveHealth(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error)

	// ReadyHealthReadyGet — Check service readiness
	//
	// @get "health/ready"
	// @bind "ready_health_ready_get"
	GetReadyHealth(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error)

	// PublicStatusV1StatusGet — Get public service status
	//
	// @get "v1/status"
	// @bind "public_status_v1_status_get"
	GetPublicStatus(ctx context.Context, mods ...aoni.RequestModifier) (*PublicStatus, error)

	// AccountV2V2AccountGet — Get the API account
	//
	// @get "v2/account"
	// @bind "account_v2_v2_account_get"
	GetAccount(ctx context.Context, mods ...aoni.RequestModifier) (*V2accountResponse, error)

	// MarketPriceV2V2SteamMarketPriceGet — Get a Steam Community Market price
	//
	// @get "v2/steam/market/price"
	// @bind "market_price_v2_v2_steam_market_price_get"
	GetSteamMarketPrice(ctx context.Context, marketHashName string, appID int, currency int, mods ...aoni.RequestModifier) (*V2marketPriceResponse, error)

	// InventoryV2V2SteamUsersSteamIDInventoryAppIDContextIDGet — Load a Steam user's inventory
	//
	// @get "v2/steam/users/{steam_id}/inventory/{app_id}/{context_id}"
	// @bind "inventory_v2_v2_steam_users__steam_id__inventory__app_id___context_id__get"
	GetSteamInventory(ctx context.Context, steamID id.ID, appID int, contextID int, cursor string, language string, mods ...aoni.RequestModifier) (*V2inventoryResponse, error)
}
