// Code generated by aoni "openapi -spec api-1.json -pkg express -base-url https://api.express-load.com/ -type-map steam_id=github.com/lemon4ksan/g-man/pkg/steam/id.ID -skip-deprecated -fast"
// 
// DO NOT EDIT.

package express

import (
	"context"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"

	"github.com/lemon4ksan/g-man/pkg/steam/id"
)

// BaseURL is the default API base endpoint.
const BaseURL = "https://api.express-load.com/"

type AccountData struct {
	APIKey         APIKeySummary `json:"api_key"`
	BalanceCredits int           `json:"balance_credits"`
	CustomerID     string        `json:"customer_id"`
	Usage          UsageSummary  `json:"usage"`
}

type APIKeySummary struct {
	ID                 string   `json:"id"`
	RateLimitPerMinute int      `json:"rate_limit_per_minute"`
	Scopes             []string `json:"scopes"`
}

type AvailabilityHour struct {
	Availability float64 `json:"availability"`
	Timestamp    string  `json:"timestamp"`
}

// BilledResponseMeta — Stable billing and rate-limit metadata for a charged API operation.
type BilledResponseMeta struct {
	CreditsCharged   int           `json:"credits_charged"`
	CreditsRemaining int           `json:"credits_remaining"`
	PriceVersion     int           `json:"price_version"`
	ProductCode      string        `json:"product_code"`
	RateLimit        RateLimitMeta `json:"rate_limit"`
	RequestID        string        `json:"request_id"`
}

type ErrorDetail struct {
	Code      string         `json:"code"`
	Detail    map[string]any `json:"detail,omitempty"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
}

type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

type HttpvalidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// InventoryErrorCode — Errors specific to Steam inventory requests.
type InventoryErrorCode string

// InventoryErrorMessage — Stable customer-facing messages specific to inventory requests.
type InventoryErrorMessage string

type InventoryPage struct {
	Assets       []SteamAsset        `json:"assets"`
	Descriptions []SteamDescription  `json:"descriptions"`
	Pagination   InventoryPagination `json:"pagination"`
	TotalCount   int                 `json:"total_count"`
}

type InventoryPagination struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

type InventoryResponse struct {
	Assets              []SteamAsset       `json:"assets"`
	Descriptions        []SteamDescription `json:"descriptions"`
	LastAssetID         *string            `json:"last_assetid,omitempty"`
	MoreItems           *int               `json:"more_items,omitempty"`
	Success             int                `json:"success"`
	TotalInventoryCount int                `json:"total_inventory_count"`
}

type MarketPriceData struct {
	LowestPrice *string `json:"lowest_price"`
	MedianPrice *string `json:"median_price"`
	Volume      *string `json:"volume"`
}

// PublicAPIErrorCode — Errors shared by public API authentication, billing, and upstream execution.
type PublicAPIErrorCode string

// PublicAPIErrorMessage — Stable customer-facing messages shared by public v2 endpoints.
type PublicAPIErrorMessage string

type PublicStatus struct {
	History   []AvailabilityHour `json:"history"`
	Services  []ServiceStatus    `json:"services"`
	Status    string             `json:"status"`
	UpdatedAt string             `json:"updated_at"`
}

// RateLimitMeta — The API-key request budget after this response.
type RateLimitMeta struct {
	LimitPerMinute int `json:"limit_per_minute"`
	Remaining      int `json:"remaining"`
	ResetSeconds   int `json:"reset_seconds"`
}

// ResponseMeta — Metadata present on every successful v2 response.
type ResponseMeta struct {
	RequestID string `json:"request_id"`
}

type ServiceStatus struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

type SteamAsset struct {
	Amount     string `json:"amount"`
	AppID      int    `json:"appid"`
	AssetID    string `json:"assetid"`
	ClassID    string `json:"classid"`
	ContextID  string `json:"contextid"`
	InstanceID string `json:"instanceid"`
}

// SteamCurrency — Supported Steam ECurrency value
type SteamCurrency int

type SteamDescription struct {
	AppID          int        `json:"appid"`
	ClassID        string     `json:"classid"`
	Commodity      *int       `json:"commodity,omitempty"`
	InstanceID     string     `json:"instanceid"`
	MarketHashName *string    `json:"market_hash_name,omitempty"`
	MarketName     *string    `json:"market_name,omitempty"`
	Marketable     *int       `json:"marketable,omitempty"`
	Name           *string    `json:"name,omitempty"`
	Tags           []SteamTag `json:"tags,omitempty"`
	Tradable       *int       `json:"tradable,omitempty"`
	Type           *string    `json:"type,omitempty"`
}

// SteamLanguage — Steam-supported localized inventory description languages.
type SteamLanguage string

type SteamTag struct {
	Category              string  `json:"category"`
	InternalName          string  `json:"internal_name"`
	LocalizedCategoryName *string `json:"localized_category_name,omitempty"`
	LocalizedTagName      *string `json:"localized_tag_name,omitempty"`
}

type UsageSummary struct {
	CreditsCharged int    `json:"credits_charged"`
	Errors         int    `json:"errors"`
	PeriodEnd      string `json:"period_end"`
	PeriodStart    string `json:"period_start"`
	Requests       int    `json:"requests"`
}

type V2AccountResponse struct {
	Data    AccountData  `json:"data"`
	Meta    ResponseMeta `json:"meta"`
	Success bool         `json:"success,omitempty"`
}

// V2ErrorDetail — Error detail for failures shared by all public v2 endpoints.
type V2ErrorDetail struct {
	Code      PublicAPIErrorCode    `json:"code"`
	Detail    map[string]any        `json:"detail,omitempty"`
	Message   PublicAPIErrorMessage `json:"message"`
	RequestID string                `json:"request_id"`
}

type V2ErrorResponse struct {
	Error   V2ErrorDetail `json:"error"`
	Success bool          `json:"success,omitempty"`
}

// V2InventoryErrorDetail — Shared public errors plus inventory-specific failures.
type V2InventoryErrorDetail struct {
	Code      any            `json:"code"`
	Detail    map[string]any `json:"detail,omitempty"`
	Message   any            `json:"message"`
	RequestID string         `json:"request_id"`
}

type V2InventoryErrorResponse struct {
	Error   V2InventoryErrorDetail `json:"error"`
	Success bool                   `json:"success,omitempty"`
}

type V2InventoryResponse struct {
	Data    InventoryPage      `json:"data"`
	Meta    BilledResponseMeta `json:"meta"`
	Success bool               `json:"success,omitempty"`
}

type V2MarketPriceResponse struct {
	Data    MarketPriceData    `json:"data"`
	Meta    BilledResponseMeta `json:"meta"`
	Success bool               `json:"success,omitempty"`
}

type ValidationError struct {
	Ctx   map[string]any `json:"ctx,omitempty"`
	Input any            `json:"input,omitempty"`
	Loc   []any          `json:"loc"`
	Msg   string         `json:"msg"`
	Type  string         `json:"type"`
}

// Client is a thread-safe HTTP API client backed by aoni.
type Client struct {
	r request.Requester
}

// New instantiates a new Client wrapper.
func New(doer aoni.RequestDoer, apiKey string, opts ...aoni.ClientOption) *Client {
	if doer == nil {
		doer = fast.NewClient()
	}

	defaultOpts := []aoni.ClientOption{
		option.WithBaseURL(BaseURL),
	}
	if apiKey != "" {
		defaultOpts = append(defaultOpts, option.WithHeader("X-API-Key", apiKey))
	}
	defaultOpts = append(defaultOpts, opts...)

	return &Client{
		r: request.AsRequester(aoni.Configure(doer, defaultOpts...)),
	}
}

// With returns a cloned Client with the given options applied.
func (c *Client) With(opts ...aoni.ClientOption) *Client {
	if len(opts) == 0 {
		return c
	}
	return &Client{
		r: request.AsRequester(aoni.Configure(c.r, opts...)),
	}
}

// R yields the underlying low-level Requester.
func (c *Client) R() request.Requester {
	return c.r
}

// GetSteamMarketPriceV2 — Get a Steam Community Market price
// Route: GET /v2/steam/market/price
func (c *Client) GetSteamMarketPriceV2(ctx context.Context, query GetSteamMarketPriceV2Query, mods ...aoni.RequestModifier) (*V2MarketPriceResponse, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithQuery(query),
		mod.WithErrorModel(&V2ErrorResponse{}),
	}, mods...)

	return request.GetTo[V2MarketPriceResponse](ctx, c.r, "v2/steam/market/price", allMods...)
}

// GetSteamMarketPriceV2Query encapsulates query parameters for the request.
type GetSteamMarketPriceV2Query struct {
	MarketHashName string        `url:"market_hash_name,omitempty"`
	AppID          int           `url:"app_id,omitempty"`
	Currency       SteamCurrency `url:"currency,omitempty"`
}

// GetAccountV2 — Get the API account
// Route: GET /v2/account
func (c *Client) GetAccountV2(ctx context.Context, mods ...aoni.RequestModifier) (*V2AccountResponse, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithErrorModel(&V2ErrorResponse{}),
	}, mods...)

	return request.GetTo[V2AccountResponse](ctx, c.r, "v2/account", allMods...)
}

// GetStatus — Get public service status
// Route: GET /v1/status
func (c *Client) GetStatus(ctx context.Context, mods ...aoni.RequestModifier) (*PublicStatus, error) {
	return request.GetTo[PublicStatus](ctx, c.r, "v1/status", mods...)
}

// CheckReady — Check service readiness
// Route: GET /health/ready
func (c *Client) CheckReady(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.GetTo[map[string]any](ctx, c.r, "health/ready", mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// CheckLive — Check process liveness
// Route: GET /health/live
func (c *Client) CheckLive(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error) {
	resp, err := request.GetTo[map[string]any](ctx, c.r, "health/live", mods...)
	if err != nil {
		return nil, err
	}
	return *resp, nil
}

// GetSteamUsersInventoryV2 — Load a Steam user's inventory
// Route: GET /v2/steam/users/{steam_id}/inventory/{app_id}/{context_id}
func (c *Client) GetSteamUsersInventoryV2(ctx context.Context, steamID id.ID, appID int, contextID int, query GetSteamUsersInventoryV2Query, mods ...aoni.RequestModifier) (*V2InventoryResponse, error) {
	allMods := append([]aoni.RequestModifier{
		mod.WithVar("steam_id", steamID),
		mod.WithVar("app_id", appID),
		mod.WithVar("context_id", contextID),
		mod.WithQuery(query),
		mod.WithErrorModel(&V2ErrorResponse{}),
	}, mods...)

	return request.GetTo[V2InventoryResponse](ctx, c.r, "v2/steam/users/{steam_id}/inventory/{app_id}/{context_id}", allMods...)
}

// GetSteamUsersInventoryV2Query encapsulates query parameters for the request.
type GetSteamUsersInventoryV2Query struct {
	Cursor   *string       `url:"cursor,omitempty"`
	Language SteamLanguage `url:"language,omitempty"`
}

// ============================================================================
// REQUEST MODIFIERS (HEADER HELPERS)
// ============================================================================

// WithIdempotencyKey returns a RequestModifier that sets the Idempotency-Key header.
func WithIdempotencyKey(value string) aoni.RequestModifier {
	return mod.WithHeader("Idempotency-Key", value)
}
